### ISSUE TITLE
Add performance metrics and graphs to the admin analytics

### ISSUE THREAD

**Issue by GUI** [18F/api.data.gov#103]
In the admin analytics, we currently return the average response time for your current query. However, it would be helpful to have a different view that charts things based on the performance of your API, so you could more easily see performance over time.

We should consider something like this, where we chart the average, as well as percentiles, to help identify outliers: http://www.elasticsearch.org/blog/averages-can-dangerous-use-percentile/

![screen-shot-2014-04-07-at-12 53 57-pm](https://cloud.githubusercontent.com/assets/12112/3780020/8b432458-1988-11e4-9b65-b1d3f15a24a2.png)

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
