### ISSUE TITLE
Rate limit "buckets" (counting agency rate limits separately)

### ISSUE THREAD

**Issue by GUI** [18F/api.data.gov#124]
Right now rate limits are counted and applied globally. To be clear, the rate limits can be adjusted on a per-API or per-user basis, but the counting of requests towards those limits happens globally. A couple examples of the current behavior might be easier to understand:
- Let's say you have two agency APIs on api.data.gov: Agency A limits requests to 1,000 requests per hour, while Agency B limits requests to 500 per hour. If a user makes 500 requests to Agency A's APIs, and then try to hit Agency B's API, they'll be told they're over the rate limits (despite the fact that they haven't made any requests to Agency B). This isn't exactly intuitive to the end-user.
- The more problematic scenario is when you give a user a custom rate limit. Taking the same example as above, let's say Agency A is working with a special partner and grants that partner's API key a custom rate limit of 10,000 requests per hour. That per-user rate limit currently has precedent over all other rate limits, so that special key can now also make 10,000 requests per hour to Agency B's API.

Basically, the current behavior is less than ideal once a single key starts to get used to access agency APIs.

To address this, I've been thinking about the concept of rate limit "buckets". When you setup a new API backend, you can choose which bucket its rate limits are counted in: the default global bucket, or a custom bucket you create. Then when counting the rate limits for a key, we basically scope its counts to whatever bucket the API backend is setup for. Then for the user-side of things, when you setup a per-user rate limit, you would basically be presented with all the buckets that exist in the system, and you could setup custom rate limits for any individual bucket.

We should consider how buckets are tied to the concept of admin API scopes and groups for admin permissions: #56 However, I don't think we want to re-use the same concept of the API permission scopes for these rate limits. The concept is similar, but those permission scopes apply to things based only on path, and I think we need a little more flexibility when it comes to rate limiting. The bucketing approach would allow us to more loosely couple and de-couple APIs for rate limiting purposes. However, we should give this a bit more thought to make sure it's not redundant, since my original thoughts for this bucketing scheme pre-date the current permission scope implementation.

**Comment by GUI** [comment]
In addition to keeping agency limits separate, here's another use-case we just ran into: https://github.com/18F/api.data.gov/issues/237 (basically keeping the DEMO_KEY limits separate from the API key signup ones to prevent unintuitive signup failures if a user exceeds their DEMO_KEY limits).

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
