### ISSUE TITLE
Complete migration of documentation off of api.data.gov 

### ISSUE THREAD

**Issue by gbinal** [18F/api.data.gov#141]
For each of these, we should migrate or deprecate the documentation since it's not intended to live on api.data.gov. 
- [ ] http://api.data.gov/docs/regulations/
- [ ] http://api.data.gov/docs/census/american-community-survey/
- [ ] http://api.data.gov/docs/fcc/broadband-map/provider/

**Comment by GUI** [comment]
Closing this, since I just checked and all the docs appear to have been moved elsewhere. The only content on api.data.gov now links off to external agency developer hubs for documentation.
