### ISSUE TITLE
Clarify that an agency wanting to use or experiment with api.data.gov won't automatically make their API public

### ISSUE THREAD

**Issue by GUI** [18F/api.data.gov#163]
I think there's been a fairly common misconception when we talk with new agencies that their API will automatically be listed on api.data.gov's home page and made public. I think we should try to clarify this somewhere so that it's clearer to interested agencies that they can experiment with api.data.gov in front of their API without anyone ever knowing. I think this might make people more comfortable with it and more likely to play with it earlier on in the development and release of new APIs (rather than thinking they have to wait until they're ready to go live).

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
