### ISSUE TITLE
Expand the "How to Participate" section

### ISSUE THREAD

**Issue by GUI** [18F/api.data.gov#164]
Right now, we have a section on the about page for how new agencies can [participate](http://api.data.gov/about/#how-to-participate). It's pretty short, and basically boils down to contact us and it's easy to get setup. While that's true, I think it might help to also lay out some of the concrete next steps in more detail, since that's a common thing we cover when talking with new agencies. In getting new agencies setup, there's been enough similarities that I think we could flush this out in a bit more detail, so agencies have a better idea of how things work.

I don't think we need to go into super technical detail on anything, but I think having a loose list of steps that will happen will help onboard new people. Something like:
1. Build your API (already have an API? Great, next step!)
2. Make the API accessible to api.data.gov servers.
3. Setup api.data.gov/agency/your-api as a proxy to your API.
4. Play around with api.data.gov in front of your API to your heart's content.
   ![](http://media.giphy.com/media/10tHozmXU5x1sI/giphy.gif)

I think we should then also highlight recommended next steps like:
- Switching to your own agency's API domain.
- Securing your API so it's only accessible via api.data.gov (so api keys and rate limits are enforced).
- Creating your own documentation and embedding our signup form there.
- Linking to your documentation on api.dat.gov's home page if you want.

Particularly the latter is probably related to: #163

And while these steps outlined do start with building your API first, I think we should also note somewhere that it's never too early to reach out to us if you haven't built an API yet, but would like to plan for using api.data.gov in future APIs.

**Comment by gbinal** [comment]
This is factored into #475, so I'm going to go ahead and close this.
