### ISSUE TITLE
Gather feedback on Lua/OpenResty prototype and speed improvements

### ISSUE THREAD

**Issue by GUI** [18F/api.data.gov#167]
More details forthcoming, but I've been prototyping some API Umbrella changes in Lua/nginx/OpenResty. As part of this sprint I need to wrap up the details of that prototype and send it out for feedback.

**Comment by gbinal** [comment]
https://groups.google.com/forum/?nomobile=true#!topic/us-government-apis/5QcbBKKD4dk

Great job with this, @GUI.

**Comment by GUI** [comment]
And to tie these issues together on GitHub, here's the issue I added with more details on the API Umbrella prototype: https://github.com/NREL/api-umbrella/issues/86
