### ISSUE TITLE
Admin Analytics: More clearly distinguish between successful requests and blocked requests in graphs

### ISSUE THREAD

**Issue by GUI** [18F/api.data.gov#172]
In the "Filter Logs" view of the admin analytics, the chart shows all the individual requests for your current search. However, it's not immediately obvious which of those requests actually succeeded. This can be particularly confusing if you're drilling into a user's recent usage, and you see a large spike of activity that exceeds the allowed rate limits. However, in reality, some of those requests may have been blocked by api.data.gov (due to rate limiting), so they never reached your server. You can determine this by performing advanced filters based on the response code, but that's not very intuitive. This has proven confusing to multiple people when they're investigating heavy usage of their API, and I agree things are not obvious.

What I would propose is that we turn the chart in the "Filter Logs" view into a stacked bar chart (similar to the "API Drilldown" view). We could then categorize and group the results by their response codes so you can very quickly see which requests are successful, versus which are blocked, versus which have errors. Binning this graph by response codes also has the added advantage of making it easier to identify API errors that might be occurring, which has been another thing I think we could do a better job in identifying.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
