### ISSUE TITLE
Add admin interface to block IP addresses

### ISSUE THREAD

**Issue by GUI** [18F/api.data.gov#183]
Currently in the admin tool, we have an easy way to disable specific API keys, but not an easy way to globally block an IP address. We can do IP-based blocks more manually on the server, but I think this would be something we should expose in the admin UI so this is easier to manage and admins can do this without us having to manually do stuff on our servers.

In this interface, we should also allow blocking of IP ranges via CIDR addresses, but we may want to be a little careful on that, so someone doesn't accidentally add something like `10.0.0.1/0` and accidentally block all IP addresses. Maybe allow any admin to block single IPs, but require superuser privileges to block ranges? And also some sanity checks to prevent something really bad like `/0`?

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
