### ISSUE TITLE
Follow up on AWS environment location/ownership

### ISSUE THREAD

**Issue by GUI** [18F/api.data.gov#196]

**Comment by GUI** [comment]
Status update: I realized I missed an e-mail from Gerard at GSA IT about this exact subject from last month (oops!). I followed up with him, Noah, and some NREL folks on Monday about figuring this out. I haven't heard back yet, but I can followup.

**Comment by GUI** [comment]
Followed up via e-mail today.

**Comment by gbinal** [comment]
This was addressed a while back.  Closing.
