### ISSUE TITLE
Mask redirects from API backends

### ISSUE THREAD

**Issue by GUI** [18F/api.data.gov#197]
When API backends return redirects, they can sometimes end up returning redirects to the underlying API's URL. For example, we've seen this on a couple different API backends that require trailing slashes something where something like this ensues:

- A user requests `https://api.data.gov/my/awesome/api`
- This is then proxied to the API backend which might live somewhere like `https://my-super-cool-site.gov/api`
- The backend wants a trailing slash so it returns a redirect for `Location: https://my-super-cool-site.gov/api/`
- api.data.gov returns that redirect header verbaitim, so the user ends up landing on `https://my-super-cool-site.gov/api/`.
- This direct URL endpoint isn't accessible by the user (since the API backend only allows access from the api.data.gov server IPs), so then the user gets a forbidden error.

This obviously isn't desirable since that underlying URL should not be visible to the user (and is likely blocked from direct access). API Backends may be able to account for the redirect URL they should return by looking at the `X-Forwarded-Host` headers we pass back (and I think some frameworks default to this), but if the URL Path has also been rewritten (eg, from `/my/awesome/api` to `/api` in the above example) then it might be tricky for an API backend to totally account for the changes in URLs.

In any case, this is definitely something that it would be nice for us to handle at the api.data.gov layer, so the API backend doesn't have to think about these potential redirect issues. It can be a little tricky for us to get this totally right at our layer (mainly if complex rewrite rules are in effect), but for the large majority of our cases where we're only changing the host and URL path prefix, this should be doable.

See something like nginx's [`proxy_redirect`](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_redirect) for reference.

A couple edge cases that come to mind to consider:

- If the API backend is using the `X-Forwarded-Host` header, but doesn't know about the URL path rewriting, the redirect coming from the API backend may contain the correct host, but an incorrect path.
- The redirect location may or may not include port information in the host portion of the response.

**Comment by cmc333333** [comment]
Breaking this into parts:

* [ ] Replace any instance of the backend domain name. This is most important as it leaks semi-sensitive information
* [ ] Properly replace backend paths. This may be required for the redirect to actually work
* [ ] Account for `api_token` if present in the original request
