### ISSUE TITLE
Log and display X-Cache response headers in analytics data

### ISSUE THREAD

**Issue by GUI** [18F/api.data.gov#227]
This is in a similar vein to https://github.com/18F/api.data.gov/issues/226. Essentially, right now we're logging the `X-Cache` response header in some of our log files, but I don't think we're actually storing it in our analytics database. This response header will contain either `HIT` or `MISS` value depending on whether we're delivering a cached result or not. I think it would be quite helpful to start persisting this header to the analytics database, and then also expose it in our admin analytics interface. This information can be quite helpful in debugging when responses are being cached, and we could also do quite a bit with this to better display cache hit rate information (to give admins a sense of how they could better utilize the caching features).

(We do currently store the `Age` response header in our analytics database, although that field is not exposed in the admin UI either right now. `Age` tells the age in seconds of a cached result, so while `Age` can also be used to determine cache hit rates, it's not quite as easy to query than a simple `HIT`/`MISS` value, and there are some edge-cases where `Age` doesn't quite work, like when a cached object is less than 1 second old. So if we're going to expose this information in the admin, I'd prefer to use the `X-Cache` header which we recently started returning and seems more straightforward for most high-levle purposes.)

**Comment by GUI** [comment]
It would still be nice to log these `X-Cache` headers and then expose that through our simpler analytics filters. But in the meantime, I thought I'd make more detailed note of how you can query this in our current analytics using the `Age` header:

- In the analytics screens click the link to "Switch to advanced filters."
- Here's an example of how to query for cached responses (with an `Age` greater than or equal to 1):

  ```
  request_host:api.data.gov AND request_path:\/example-agency* AND response_age:[1 TO *]
  ```

- Similarly, here's how you might filter for uncached responses (`Age` equal to 0--as noted above this isn't exactly a perfect approach, since it may not count requests that have been cached for less than a second as being cached, but it should generally be very close):

  ```
  request_host:api.data.gov AND request_path:\/example-agency* AND response_age:0
  ```

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
