### ISSUE TITLE
Automatically optimize monthly elasticsearch indexes when new months roll around

### ISSUE THREAD

**Issue by GUI** [18F/api.data.gov#228]
This has been on the backburner for a long time, but as our analytics database grows, I think this becomes more important to help keep things performing decently.

For all of our analytics data we store in ElasticSearch, we bin the data into monthly indexes. This means that when a new month rolls around, the previous month's worth of data will then remain static. Since we'll no longer be inserting records into previous month indexes, we can see decent performance gains in our ability to query that old data by [optimizing](http://www.elastic.co/guide/en/elasticsearch/reference/current/indices-optimize.html) the old indexes with a `max_num_segments: 1`.

We don't currently perform this optimization, but I think some of our admin analytics queries (particularly historical ones), could see benefits if we automatically performed this optimization for each old index.

What I'm possibly envisioning is that one of our logger background processes could periodically check (maybe every night?) to see if there are any old indexes to optimize, and then if so, perform those optimizations in the background. And while usually we would just need to optimize the previous month's index, I think it might be worth having this background job look at all the stats on the available indexes to see which indexes should be optimized (rather than just hardcoding month -1). Since if we ever bulk reprocess data or import data (which we do from time-to-time), then it would be nice to just have this same process pick up all the old indexes that need optimizing and perform it as part of the normal nightly run. However, we should be careful _not_ to ever optimize the current month's index, since that will probably cause unnecessary churn for an index file that's still being appended to.

**Comment by GUI** [comment]
I unfortunately wasn't able to get to this. I also can't find the script where I had essentially implemented this. Oops! But in any case, it wasn't a very complex script, it just inspected all the current indexes, looked for any with more than the expected segments, and then ran an optimize with `max_num_segments: 1` on each one that appeared unoptimized (and wasn't the current month, since we want to leave the current month unoptimized). All I was really thinking of doing was shifting this kind of thing into some `setInterval` background task in perhaps the [log-processor](https://github.com/NREL/api-umbrella-router/blob/master/bin/api-umbrella-log-processor).

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
