### ISSUE TITLE
User can be prevented from signing up for their own API key due to rate limiting

### ISSUE THREAD

**Issue by GUI** [18F/api.data.gov#237]
Our API key signup form uses an internal API to perform the actual signup action. However, we apply a much lower rate limit (per IP) to this signup API to prevent potential abuse (mainly to prevent bots from signing up from hundreds or thousands of API keys per day). However, this low rate limit leads to this potential problem:
- Let's say a user is exploring an API and uses the [DEMO_KEY](http://api.data.gov/docs/rate-limits/#demokey-rate-limits) to make 30 requests within an hour.
- On their 31st request within an hour using DEMO_KEY they receive an over rate limit error and are told to go signup for an API key.
- If they signup within that same hour, the user will receive a signup error due to their IP address having exceeded their total rate limits for the hour. This is because they've already made 30 requests in the hour, and our default recommended rate limits for the key signup API is actually below this (currently 20 requests per hour).

I don't think users have hit this scenario very often, which is a good thing, but it's also somewhat surprising, since this seems like a pretty reasonable path towards signing up for an API key. But if the user waits until the next hour, they should be able to signup fine, so this may also be why most users haven't encountered it.

One potential quick fix would be to make the key signup API have higher rate limits than DEMO_KEY (maybe 35-40 instead of 20). Longer term, this would be a good candidate for separate rate limit buckets as outlined in this issue: https://github.com/18F/api.data.gov/issues/124 That would allow the DEMO_KEY limits to be kept separate from the signup limits so these hits from the same IP address wouldn't be competing against each other.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
