### ISSUE TITLE
API key signup unexpectedly failed.

### ISSUE THREAD

**Issue by ekivemark** [18F/api.data.gov#245]
I am attempting my first integration with api.data.gov using a prototype platform in AWS (dev.bbonfhir.com).

When I try to incorporate the signup form I get 

API key signup unexpectedly failed.

Please try again or contact us for assistance.
- Mark

**Comment by ekivemark** [comment]
The error also appears off screen 
![2015-06-12_14-35-27](https://cloud.githubusercontent.com/assets/104304/8137295/4e2b3a80-1110-11e5-8664-eccfac1bc353.png)

**Comment by ekivemark** [comment]
If you resize the browser screen to smartphone size the error appears. I also tried this in chrome as well as Safari with same result.

Here it is resized to smartphone screen size....

![2015-06-12_14-37-26](https://cloud.githubusercontent.com/assets/104304/8137330/99629a8e-1110-11e5-8832-f2ad65236adb.png)

**Comment by GUI** [comment]
@ekivemark: I believe the issue might be with the "Restrict Access to HTTP Referers" field setup on your API key. Right now it reads `*//dev.bbonfhir.com/*`, but when I go to that site, I get redirected to an AWS URL. You'll need to add any URLs to the "Restrict Access to HTTP Referers" that your browser may be using on the signup page. So for example, you might try adding another entry of `*//http://ec2-54-165-75-7.compute-1.amazonaws.com/*` to that field. Let us know if that doesn't do the trick.

Regarding the popup showing up off screen, that's a bit odd. It seems like there might be conflicting CSS styles between our signup form and the your site. We attempt to scope all of our styles to be unique to prevent these type of conflicts, but we might be missing something. Is this demo page publicly accessible? If so, I could try to debug it further.

**Comment by ekivemark** [comment]
Nick,

Thanks for the quick response. 

I have a login working that sends email. So just register and then in the activation email click on the Manage Accounts link to get to your form.

BTW - I have added the AWS url but had to do so without the http:// prefix. It worked!  Thanks!




Regards

Mark Scrimshire
CMS/HHS Entrepreneur-in-Residence <http://ekivemark.com/>

Cell: +1.703.623.2789 <skype:ekivemark?call>
Desk: +1.410.786.5049
email: mark@ekivemark.com <mailto:mark@ekivemark.com>
Stay up-to-date: Twitter @ekivemark <http://twitter.com/ekivemark>

**Comment by tariq452** [comment]
Dear i have the sam problem API key signup unexpectedly failed.

**Comment by GUI** [comment]
Going to (belatedly) close this, since it sounds like this was resolved, but feel free to open a new issue if anyone's still running into this.
