### ISSUE TITLE
logs.json reloaded multiple times

### ISSUE THREAD

**Issue by cmc333333** [18F/api.data.gov#250]
Watch the network activity on a page like `/admin/#/stats/logs`. Particularly if you filter, you'll see that the data file (logs.json) is retrieved several times. We expect one load on page load and another per filter submission.

**Comment by GUI** [comment]
Thanks for catching this! I think this may have also been exacerbating some of our analytics performance issues, so this is definitely good to fix. I've gone ahead and deployed a fix for this to production (https://github.com/NREL/api-umbrella-web/pull/20).
