### ISSUE TITLE
Add API endpoint for admins to be able to purge cached content on demand

### ISSUE THREAD

**Issue by GUI** [18F/api.data.gov#252]
Since api.data.gov provides a caching layer that supports [Surrogate-Control](http://apiumbrella.io/docs/caching/#surrogate-control), it would also be useful if we exposed an API for admins to be able to purge their cached content. This is particularly relevant when `Surrogate-Control` is being used, since this allows API owners to more tightly control what gets cached at the API Umbrella layer, so allowing the same API owners to purge content on demand would also be very useful.

While most caching servers have a built-in API for purging content, we'd need to wrap that up some how so that external admins can access it via an API that also validates the admin's permissions (so Agency X admins can only purge Agency X content, and not content from Agency Y).

A few random notes:
- Currently we're using Varnish for our caching layer, but if feasible, I'd like to make the API we expose independent of the underlying cache server. The reason is that I'd still like to have the possibility of switching to [nginx's builtin caching](https://github.com/NREL/api-umbrella/issues/86) or [trafficserver](https://github.com/NREL/api-umbrella/issues/35) without breaking this piece of functaionltiy
  - I need to update those issues, but the current direction I'm leaning is TrafficServer for possible future updates, since nginx's caching won't work with streaming respones, and TrafficServer has been more reliable and faster than Varnish in my tests and experiences.
  - I think most all of these support a basic `PURGE` mechanism for clearing single URL endpoints. However, Varnish's ban lists are a pretty nice way to handle purging wildcard URLs efficiently, so it would be nice to figure out a way to implement that without necessarily tying us to the ban list feature directly. I don't think TrafficServer has a similar concept, but I vaguely recall seeing something on their mailing list about a plugin or some other different approach for dealing with this kind of thing (I can't find it now).
- For reference, see [Fastly's purging API](https://docs.fastly.com/api/purge) for a nicely documented purging API approach. They don't support wildcards, but they do support a purge based on a `Surrogate-Key`, which is an interesting alternative approach that might be more feasible to implement efficiently across caching serves. I also like their ability to distinguish between what they call soft purges (stale while revalidate) vs a hard purge (wiped immediately).

**Comment by harrisj** [comment]
So, this would be a highly useful feature for us on the FBI Crime Data Explorer. Agency-specific endpoints are generally the slowest ones for us, and also the one least likely to get repeated cache hits before expiration (because there are so many more agencies than states and such). Since this data doesn't get updated more than once a year, it would be cool to just cache agency results for months and purge it when we need to.

**Comment by b238** [comment]
I agree!

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
