### ISSUE TITLE
always get JS error at: https://api.data.gov/admin/#/apis

### ISSUE THREAD

**Issue by ultrasaurus** [18F/api.data.gov#254]
may be related to: https://github.com/18F/api.data.gov/issues/253

on https://api.data.gov/admin I get a JS error about half the time, but I've never been able to successfully load: https://api.data.gov/admin/#/apis

Here's what I see:
![image](https://cloud.githubusercontent.com/assets/41906/8431058/98c350f8-1eeb-11e5-94be-e1a3dd7a94b1.png)

**Comment by cmc333333** [comment]
I'm betting that one of the admin servers is out of date and referencing the wrong file. When the page does load (for me), it's referencing https://api.data.gov/web-assets/admin-4b2d2624d12776931bbb22016e29eb4d.js

When it does not, it's referencing https://api.data.gov/web-assets/admin-1ab7c277a495646e6ed6b4cd595f720d.js

I will look through the docs today and try deploying admin.

**Comment by cmc333333** [comment]
I think I tracked this down to a webserver which did not receive the proper updates. Looks okay now; please reopen if the issue comes back up.
