### ISSUE TITLE
Simpler Agency Email Lookup

### ISSUE THREAD

**Issue by cmc333333** [18F/api.data.gov#256]
Right now, when we receive agency-specific feedback in our common feedback form, the process for determining who to notify is painful.

In the admin, I go to Admin Groups to find the relevant group, then must page through the Admin Accounts (sorting by Groups does not work) to find them. It'd be nicer if the Admin Group profile page contained a list of all associated users.

**Comment by GUI** [comment]
Well, I finally got around to trying to improve this (selfishly, so I could tackle purging admin accounts and notifying admin groups with a lot less pain: https://github.com/18F/api.data.gov/issues/326).

The interface is still pretty basic, and I think there's more we could do to improve the interface and user management flow, but hopefully these couple of basic additions will help with the bulk of our lookup needs. But let me know if you have any other preferences or thoughts.

What changed (https://github.com/NREL/api-umbrella/commit/9175d6088374d37f13528166d806701ee0cd9bad):

- In the groups listing, the e-mail addresses of all the admins belonging to that group are listed in the table.
![screen shot 2016-05-13 at 9 43 50 am](https://cloud.githubusercontent.com/assets/12112/15253469/ab058ae8-18ef-11e6-9e22-4967331e0f04.png)
- When editing a single group, the members of that group are listed again, along with a link to edit the individual admin account, and the timestamp of when the admin last logged in.
![screen shot 2016-05-13 at 9 44 12 am](https://cloud.githubusercontent.com/assets/12112/15253496/c92f9be4-18ef-11e6-83ca-4002462a2f03.png)
