### ISSUE TITLE
Add new agency users to api.data.gov homepage

### ISSUE THREAD

**Issue by gbinal** [18F/api.data.gov#257]
* nasa 
* calc
* who else?

**Comment by timwood** [comment]
Commerce?

**Comment by gbinal** [comment]
:)  About to follow up, Tim.  Sorry for the slow response.

**Comment by gbinal** [comment]
Ed

**Comment by gbinal** [comment]
openfec

**Comment by gbinal** [comment]
LoC

**Comment by GUI** [comment]
@gbinal: I [added](https://github.com/18F/api.data.gov/commit/2796dde02dce2c50bdb46b3da4d45fd1cf7f8f25) the following:

- NASA
- FEC
- ED
- Commerce
- BBG
- BusinessUSA

I think that covers everyone, but let me know if you can think of anyone else. You had mentioned CALC and LoC, but I can't find any public API docs for CALC (although I might just be missing them) and I don't think LoC has gone live.

I'm going to go ahead and close this one, but if you want any tweaks to how anything is organized, just give a shout. (for example, I wasn't sure if BusinessUSA fell under another agency, so I stuck it at the top-level sort of like regulations.gov).

**Comment by gbinal** [comment]
:+1:

**Comment by timwood** [comment]
Thanks for including Commerce!  :clap:
