### ISSUE TITLE
Proposed change in description of repo.

### ISSUE THREAD

**Issue by melodykramer** [18F/api.data.gov#263]
Hi,

I'm going through all of our repos and making sure they're consistent and accessible. The description of this repo in Tock is "A hosted, shared-service that provides an API key, analytics, and proxy solution for government web services."

Would it be possible to change the description of this repo to that, to make it consistent? Alternatively, the description on the website for api.data.gov is 'api.data.gov is a free API management service for federal agencies. Our aim is to make it easier for agencies to release and manage APIs." This would also be a more descriptive description.

Mel

**Comment by GUI** [comment]
Updated with your recommendation. Thanks!
