### ISSUE TITLE
deprecate myusa login for admins 

### ISSUE THREAD

**Issue by gbinal** [18F/api.data.gov#268]

**Comment by GUI** [comment]
Oops, I had chatted with @NoahKunin about this last week, but I forgot to followup. Sorry about that! But thanks for the reminder.

I've gone ahead and removed MyUSA as a login option from the admin tool, so I think we should be set. I also e-mailed all of the admin users who last used MyUSA to login to let them know. But all of the previous users were actually `@gsa.gov`, so I'm hoping that means nobody will have any issues logging in with their Google Accounts as an easy alternative.
