### ISSUE TITLE
Run integration tests in real browsers with Selenium

### ISSUE THREAD

**Issue by GUI** [18F/api.data.gov#272]
We currently have a variety of automated integration tests for the admin tool (to test its behavior in a browser stack with JavaScript enabled). However, currently we're using phantomjs for these tests, so while our tests run in a webkit environment that's close to Chrome or Safari, it's not quite a real browser, and this also means we're not performing our automated tests in Firefox or IE. As an example of when this can lead to things breaking, we had test coverage for #271 in place, but since the bug was specific to Firefox, it wasn't caught by our automated test suite. We should explore running our integration tests via a Selenium service, like [Sauce Labs](https://saucelabs.com) (they provide a free account for open source projects). This would allow us to run our existing tests in a variety of actual browsers, so we can more easily ensure we don't have cross-browser issues.

We're using Capybara for our existing test suite, which should give us the ability to easily switch our existing phantomjs-based tests to run in Selenium without having to change any code. I toyed around a bit with that today, but hit some roadblocks with the tests not logging into our admin when executed in the Selenium environment. This might be related to our mocking of the login process in our feature tests, and we may need to actually hop through the login process each time (which is a more realistic tests, it's just a bit slower). So this might require a bit of extra time to figure out how to get everything running properly in Selenium, but it would be super nice to have these tests running across a variety of real browsers and operating systems.

**Comment by gbinal** [comment]
This is done.
