### ISSUE TITLE
research api status provider options

### ISSUE THREAD

**Issue by gbinal** [18F/api.data.gov#273]
Hosted:  
- https://www.statuspage.io/
- https://www.status.io/
- https://statushub.io/
- http://www.offsitestatus.com/
- https://projectpulse.io/
- https://www.hostedstatuspage.com/

Open Source: 
- http://www.stashboard.org/
- https://cachethq.io/
- http://www.system-status-dashboard.com/

**Comment by mogul** [comment]
Thanks for gathering these up! Are you thinking that api.data.gov would supply one transparently for any API it's helping manage? (I can also imagine adding one of the open source ones to the Cloud Foundry service broker for any hosted service to instantiate on demand, not just for APIs...!)

**Comment by gbinal** [comment]
>  Are you thinking that api.data.gov would supply one transparently for any API it's helping manage?

Yep.  

> I can also imagine adding one of the open source ones to the Cloud Foundry service broker for any hosted service to instantiate on demand, not just for APIs...!

I hear you though would be of a mind to keep this to APIs to avoid scope creep.  Suss out 18F providing a wider omnibus service and I'm game but in the meantime, I want to make sure that my reach doesn't exceed my grasp.

**Comment by jbrooksuk** [comment]
I'm the founder of Alt Three, the company behind Cachet. If you have any questions, please ask, I'm happy to help!

**Comment by gbinal** [comment]
Thanks.  We'll reach out if we need.

**Comment by arowla** [comment]
Would probably be good to keep this service out of our own hosting environment, as well, since what we'll often need to monitor will be our own APIs.

**Comment by gbinal** [comment]
Yep - we were just discussing that.

**Comment by jbrooksuk** [comment]
As I said, if you need anything from Cachet let me know and we'll see what we can sort for you :)

**Comment by gbinal** [comment]
This remains something that would be nice to have but isn't required.  I'm going to go ahead and close this for now.
