### ISSUE TITLE
Revisit e-mail requirements for signup and agency signup forms

### ISSUE THREAD

**Issue by GUI** [18F/api.data.gov#280]
We currently require e-mail verification for api keys created via the api.data.gov/signup form. This is primarily due to abuse we saw against regulations.gov. Since the e-mail verification is leading to signup issues on other services due to finicky spam filters (see https://github.com/18F/api.data.gov/issues/264), we may want to revisit this requirement on the default api.data.gov signup form. So there's maybe two sides of this:
- Revisit https://github.com/18F/api.data.gov/issues/142 and do another audit to try to get as many agencies as possible using their own API key signup form (rather than linking to our default one) where they don't have to have the e-mail verification flow.
- Revisit the default api.data.gov signup form requiring e-mail verification (but I think we'd need to check the status of regulations.gov having their own documentation website so they could still have their own signup form requiring e-mail verification).

**Comment by shawnjohnson** [comment]
Regulations.gov now has their own API key signup page - http://regulationsgov.github.io/developers/key/

**Comment by gbinal** [comment]
This can be closed.
