### ISSUE TITLE
Real-time alerting based on API backend usage or errors

### ISSUE THREAD

**Issue by GUI** [18F/api.data.gov#283]
I think we've discussed this feature before, and it's come up a few times recently in conversations, but apparently I keep forgetting to file an issue. In any case, the basic idea is that we could do various types of alerting to API owners based on the requests going through api.data.gov and the analytics we derive from that.

For a few quick examples:
- Alert if there's a sudden spike in requests being rejected due to over rate limits.
  - More specifically, an API owner may not be interested in these alerts from all IPs or API keys (since bots/malicious users may trigger this), but they may just want to be alerted when a specific key gets rate limited (for example, from their own applications).
- Alert based on increase in API response times.
- Alert based on increase in error rates or unresponsive API backends

Note, there's certainly aspects of this that are related to the general API status and monitoring we've recently discussed as part of https://github.com/18F/api.data.gov/issues/273 But this kind of functionality might be slightly different, since this information would be derived from the analytics of the actual production traffic to the API, rather than just alerting based on static health checks. This also opens the door for new types of alerting, like detecting over rate limit spikes, that's not really possible with a simple, static health check approach.

This kind of alerting could certainly become complicated, and I'm not sure it's something we really want to reinvent the wheel implementing ourselves. Some potential ideas are to look at having optional integration between API Umbrella and some other external service like New Relic to handle this kind of thing. Or on the open-source side of things, we could explore things like [ElastAlert](https://github.com/yelp/elastalert), which could tie into our ElasticSearch data.

**Comment by gbinal** [comment]
We're not likely to add this functionality any time soon, so I'm going to close for now.
