### ISSUE TITLE
"contact us" link when not yet an admin is not useful

### ISSUE THREAD

**Issue by hollyallen** [18F/api.data.gov#284]
I tried to log into api.data.gov/admin today. I selected "Login with Google", selected my GSA account, authorized api.data.gov to access the required info in my Google account, then received this error message: "The account for 'holly.allen@gsa.gov' is not authorized to access the admin. Please contact us for further assistance."

The text "contact us" is a link, but to "https://api.data.gov/admin/login" which is not very helpful.

**Comment by GUI** [comment]
Indeed, that sounds distinctly unhelpful for a "contact us" link. :) Thanks for the heads up!

We'll look to get that fixed, but in the short-term, can we help get your admin account setup? I assume this is for the College Scorecard API? If so, just let me know and I can create your admin account now.

**Comment by hollyallen** [comment]
Yes please!

**Comment by GUI** [comment]
@hollyallen: You should be all set to access the admin now. Give a holler if you have any questions or trouble logging in.
