### ISSUE TITLE
Roadmap / next steps

### ISSUE THREAD

**Issue by GUI** [18F/api.data.gov#295]
We had been discussing what we want to tackle next for api.data.gov. We already have some issues covering some of the topics we're considering, but as a broader overview to help us plan, here were a few distinct areas of focus that things seemed to be lumped into:
- **New Features & Functionality:** There are a couple larger and somewhat distinct features we've had rolling around as ideas for a while. The primary one we had just started to explore a couple months ago was providing some type of API monitoring, alerting, and status page. See these existing issues for some further info: https://github.com/18F/api.data.gov/issues/273 https://github.com/18F/api.data.gov/issues/283
- **Agency Signup Self-Service:** After we get agencies initially setup in api.data.gov, we've worked to make sure they can be largely autonomous in managing their APIs, users, etc (we never want to be a bottleneck). However, that initial setup is still something we need to be involved in, so it would be nice if we could remove ourselves as a blocker from that step and let agencies signup completely on their own. This initial step is primarily manual because we have to carve out initial permissions for them on the api.data.gov URL namespace or setup permissions on their own domain. If they're using their own domain, we then have to sort out SSL setup. With [Let's Encrypt](https://letsencrypt.org) I'm now hopeful we can just handle SSL for them automatically. For permissions we could probably automate that somehow (if they're using their own domain, we could use the common practice of having them prove ownership by uploading a file or changing DNS).
- **Analytics Revamp:** As part of the Lua revamp we're currently rolling out, we've improved some aspects of the analytics underbelly (mainly this issue: https://github.com/18F/api.data.gov/issues/233). However, the performance of the analytics system for admin queries is probably the biggest technical issue we still face that could potentially hamper growth. In short, the performance of the ad-hoc queries admins can run will degrade with more usage of the system. We can improve things by throwing more hardware at the problem, but that doesn't feel like a particularly sustainable or efficient solution. Here's more details: https://github.com/18F/api.data.gov/issues/235
- **Smaller Fixes & Tweaks:** This is sort of a catch-all for focusing some concerted time on smaller fixes, annoyances, little features, cleanup, etc. Probably a decent number of the issues in the backlog of this repo could fall under this category. A few random examples: making it easier to determine which admins are in a group (https://github.com/18F/api.data.gov/issues/256), passing additional x-forwarded-\* headers to API backends (https://github.com/18F/api.data.gov/issues/260), redirect website content to HTTPS (https://github.com/18F/api.data.gov/issues/211), empty listing bullet in a signup error message (https://github.com/18F/api.data.gov/issues/246), etc.

**Comment by gbinal** [comment]
Most of this has launched or is otherwise factored into work that's already in place.  I'm going to go ahead and close this.
