### ISSUE TITLE
Suggestion: Add "Retry-After" response header

### ISSUE THREAD

**Issue by shawnjohnson** [18F/api.data.gov#310]
As noted in section 14.37 - https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html.

I periodically receive questions as to how to know (programmatically) when a user can try again after they hit the rate limit. Users may benefit from this additional information.

I borrowed the idea from Sauce Labs recent announcement on rate limits.
http://sauceio.com/index.php/2016/02/announcing-new-rest-api-usage-limits/

**Comment by GUI** [comment]
Good idea. We'll definitely look to add this.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
