### ISSUE TITLE
Need to remove Persona login option

### ISSUE THREAD

**Issue by GUI** [18F/api.data.gov#311]
Mozilla is shutting down Persona on November 30, 2016: https://groups.google.com/forum/#!msg/mozilla.dev.identity/mibOQrD6K0c/kt0NdMWbEQAJ

Since we offer Persona as one of the login options for the admin tool, this is just a reminder that we need to deal with this sometime before then.
- We should look for any admin accounts that have been logging in with Persona and reach out to those users. Instruct them on how they could signup with a Google Account with that same e-mail address or use MAX.gov. We should also offer to switch their e-mail address if they'd prefer to login under some other account (for example, if they have a preferred google account under a different e-mail address).
- After giving people enough time to respond and deal with any changes, we can then remove persona from the login options (controlled via the `web.admin.auth_strategies.enabled` settings in `/etc/api-umbrella/api-umbrella.yml`).

**Comment by cmc333333** [comment]
That's rather sad

**Comment by GUI** [comment]
Step 1 is done of notifying all the admins using Persona about the change (although I had meant to do that much sooner--oops!). We can complete the second step of removing the button later this week (once it's officially gone after tomorrow).

**Comment by GUI** [comment]
Well, it's very belated, but I finally removed the Persona login button: https://github.com/18F/api.data.gov-ops/commit/ab4be720d9607368fb47aaa08462c5513068ce1e
