### ISSUE TITLE
Setup a public page to report our historical service availability

### ISSUE THREAD

**Issue by GUI** [18F/api.data.gov#312]
We had been sharing New Relic's SLA report with clients about our historical availability. However, it turned out we we are on the free Synthetics account in New Relic, so they recently cut our report down so it only shows the past few weeks. We'd like to make sure we have something similar going forward, so we have easy link to share showing a good chunk of our historical availability (preferably over maybe 1 year, broken down by weeks/months).

Since we already have a Pingdom account, we could probably use that moving forward, we just need to verify that the public reports we can get out of that would be appropriate for this type of long-term, historical reporting. It would also be nice if the reported percentages were a little more accurate than what New Relic's reports seemed to round to (since, for example, when we had a ~2 minute partial outage last fall, New Relic rounded that to 100% uptime for the month, but I'd like to be more transparent in accounting for any issues we might have).

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
