### ISSUE TITLE
508 Issues from pa11y-rails

### ISSUE THREAD

**Issue by nickbristow** [18F/api.data.gov#320]
I've run an automated scan and found the following issues. (HTML_CodeSniffer) 
Most of these errors are from color contrast on the links. 
Please feel free to ping me if you have questions. 
## Results for api.data.gov:
- **Error:** This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.63:1. Recommendation: change text colour to #317ab9.
  - WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
  - html > body > header > div:nth-child(1) > div > div:nth-child(1) > div:nth-child(1) > a
  - `<a href="main" class="local-link">Jump to Content</a>`
- **Error:** This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.63:1. Recommendation: change text colour to #317ab9.
  - WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
  - #main > div:nth-child(2) > div:nth-child(3) > div:nth-child(1) > ul > li:nth-child(1) > a
  - `<a href="/docs/bbg/">Broadcasting Board of Governors</a>`
- **Error:** This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.63:1. Recommendation: change text colour to #317ab9.
  - WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
  - #main > div:nth-child(2) > div:nth-child(3) > div:nth-child(1) > ul > li:nth-child(2) > a
  - `<a href="/docs/business-usa/">BusinessUSA.gov API</a>`
- **Error:** This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.63:1. Recommendation: change text colour to #317ab9.
  - WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
  - #main > div:nth-child(2) > div:nth-child(3) > div:nth-child(1) > ul > li:nth-child(3) > a
  - `<a href="/docs/usda/">Department of Agriculture</a>`
- **Error:** This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.63:1. Recommendation: change text colour to #317ab9.
  - WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
  - #main > div:nth-child(2) > div:nth-child(3) > div:nth-child(1) > ul > li:nth-child(4) > a
  - `<a href="/docs/commerce/">Department of Commerce</a>`
- **Error:** This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.63:1. Recommendation: change text colour to #317ab9.
  - WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
  - #main > div:nth-child(2) > div:nth-child(3) > div:nth-child(1) > ul > li:nth-child(5) > a
  - `<a href="/docs/ed/">Department of Education</a>`
- **Error:** This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.63:1. Recommendation: change text colour to #317ab9.
  - WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
  - #main > div:nth-child(2) > div:nth-child(3) > div:nth-child(1) > ul > li:nth-child(6) > a
  - `<a href="/docs/fcc/">Federal Communications Commissi...</a>`
- **Error:** This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.63:1. Recommendation: change text colour to #317ab9.
  - WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
  - #main > div:nth-child(2) > div:nth-child(3) > div:nth-child(1) > ul > li:nth-child(7) > a
  - `<a href="/docs/fec/">Federal Election Commission</a>`
- **Error:** This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.63:1. Recommendation: change text colour to #317ab9.
  - WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
  - #main > div:nth-child(2) > div:nth-child(3) > div:nth-child(1) > ul > li:nth-child(8) > a
  - `<a href="/docs/fda/">Food and Drug Administration</a>`
- **Error:** This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.63:1. Recommendation: change text colour to #317ab9.
  - WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
  - #main > div:nth-child(2) > div:nth-child(3) > div:nth-child(1) > ul > li:nth-child(9) > a
  - `<a href="/docs/gsa/">General Services Administration</a>`
- **Error:** This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.63:1. Recommendation: change text colour to #317ab9.
  - WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
  - #main > div:nth-child(2) > div:nth-child(3) > div:nth-child(1) > ul > li:nth-child(10) > a
  - `<a href="/docs/nasa/">National Aeronautics and Space ...</a>`
- **Error:** This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.63:1. Recommendation: change text colour to #317ab9.
  - WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
  - #main > div:nth-child(2) > div:nth-child(3) > div:nth-child(1) > ul > li:nth-child(11) > a
  - `<a href="/docs/nih/">National Institutes of Health</a>`
- **Error:** This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.63:1. Recommendation: change text colour to #317ab9.
  - WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
  - #main > div:nth-child(2) > div:nth-child(3) > div:nth-child(1) > ul > li:nth-child(12) > a
  - `<a href="/docs/nrel/">National Renewable Energy Labor...</a>`
- **Error:** This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.63:1. Recommendation: change text colour to #317ab9.
  - WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
  - #main > div:nth-child(2) > div:nth-child(3) > div:nth-child(1) > ul > li:nth-child(13) > a
  - `<a href="/docs/regulations/">Regulations.gov API</a>`
- **Error:** This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.63:1. Recommendation: change text colour to #317ab9.
  - WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
  - #main > div:nth-child(2) > div:nth-child(3) > div:nth-child(2) > ul > li > a
  - `<a href="/signup">Get an API Key</a>`
- **Error:** This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.63:1. Recommendation: change text colour to #317ab9.
  - WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
  - #main > div:nth-child(2) > div:nth-child(6) > a
  - `<a href="https://github.com/18F/api.data.gov/blob/master/source/index.html.erb">Help Improve this Content</a>`
- **Error:** This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.16:1. Recommendation: change text colour to #2770af.
  - WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
  - #menu-primary-navigation-1 > li:nth-child(1) > a
  - `<a href="http://catalog.data.gov/dataset" class="local-link">Data</a>`
- **Error:** This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.16:1. Recommendation: change text colour to #2770af.
  - WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
  - #menu-primary-navigation-1 > li:nth-child(2) > a
  - `<a class="dropdown-toggle local-link" data-toggle="dropdown" data-target="#" href="http://data.gov/communities/">Topics <b class="caret"></b></a>`
- **Error:** This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.16:1. Recommendation: change text colour to #2770af.
  - WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
  - #menu-primary-navigation-1 > li:nth-child(3) > a
  - `<a href="http://data.gov/impact/" class="local-link">Impact</a>`
- **Error:** This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.16:1. Recommendation: change text colour to #2770af.
  - WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
  - #menu-primary-navigation-1 > li:nth-child(4) > a
  - `<a href="http://data.gov/applications" class="local-link">Applications</a>`
- **Error:** This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.16:1. Recommendation: change text colour to #2770af.
  - WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
  - #menu-primary-navigation-1 > li:nth-child(5) > a
  - `<a href="http://data.gov/developers/" class="local-link">Developers</a>`
- **Error:** This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.16:1. Recommendation: change text colour to #2770af.
  - WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
  - #menu-primary-navigation-1 > li:nth-child(6) > a
  - `<a href="/contact/" class="local-link">Contact</a>`
- **Error:** This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.16:1. Recommendation: change text colour to #2770af.
  - WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
  - #menu-footer > li:nth-child(1) > a
  - `<a href="http://data.gov/about" class="local-link">About</a>`
- **Error:** This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.16:1. Recommendation: change text colour to #2770af.
  - WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
  - #menu-footer > li:nth-child(2) > a
  - `<a href="http://data.gov/open-gov/" class="local-link">Open Government</a>`
- **Error:** This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.16:1. Recommendation: change text colour to #2770af.
  - WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
  - #menu-footer > li:nth-child(3) > a
  - `<a href="http://data.gov/faq" class="local-link">FAQ</a>`
- **Error:** This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.16:1. Recommendation: change text colour to #2770af.
  - WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
  - #menu-footer > li:nth-child(4) > a
  - `<a href="http://data.gov/media-inquiries/" class="local-link">Media</a>`
- **Error:** This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.16:1. Recommendation: change text colour to #2770af.
  - WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
  - #menu-footer > li:nth-child(5) > a
  - `<a href="http://data.gov/glossary" class="local-link">Glossary</a>`
- **Error:** This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.16:1. Recommendation: change text colour to #2770af.
  - WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
  - #menu-footer > li:nth-child(6) > a
  - `<a href="http://data.gov/metrics" class="local-link">Federal Agency Participation</a>`
- **Error:** This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.16:1. Recommendation: change text colour to #2770af.
  - WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
  - #menu-footer > li:nth-child(7) > a
  - `<a href="http://data.gov/agencies/" class="local-link">Data Publishers</a>`
- **Error:** This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.16:1. Recommendation: change text colour to #2770af.
  - WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
  - #menu-footer > li:nth-child(8) > a
  - `<a href="http://data.gov/accessibility" class="local-link">Accessibility</a>`
- **Error:** This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.16:1. Recommendation: change text colour to #2770af.
  - WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
  - #menu-footer > li:nth-child(9) > a
  - `<a href="http://data.gov/data-policy" class="local-link">Data Policy</a>`
- **Error:** This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.16:1. Recommendation: change text colour to #2770af.
  - WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
  - #menu-footer > li:nth-child(10) > a
  - `<a href="http://data.gov/privacy-policy" class="local-link">Privacy Policy</a>`
- **Error:** This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.16:1. Recommendation: change text colour to #2770af.
  - WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
  - #menu-footer > li:nth-child(11) > a
  - `<a href="http://performance.gov" class="local-link">Performance.gov</a>`
- **Error:** This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.16:1. Recommendation: change text colour to #2770af.
  - WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
  - #menu-footer > li:nth-child(12) > a
  - `<a href="http://usa.gov" class="local-link">USA.gov</a>`
- **Error:** This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.16:1. Recommendation: change text colour to #2770af.
  - WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
  - #menu-footer > li:nth-child(13) > a
  - `<a href="http://data.gov/wp-login.php" class="local-link">Log In</a>`
- **Error:** This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.16:1. Recommendation: change text colour to #2770af.
  - WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
  - #menu-social_navigation > li:nth-child(1) > a > span
  - `<span>Twitter</span>`
- **Error:** This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.16:1. Recommendation: change text colour to #2770af.
  - WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
  - #menu-social_navigation > li:nth-child(2) > a > span
  - `<span>Github</span>`
- **Error:** This button element does not have a name available to an accessibility API. Valid names are: title attribute, element content.
  - WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.Button.Name
  - #cboxPrevious
  - `<button id="cboxPrevious"></button>`
- **Error:** This button element does not have a name available to an accessibility API. Valid names are: title attribute, element content.
  - WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.Button.Name
  - #cboxNext
  - `<button id="cboxNext"></button>`
- **Error:** This button element does not have a name available to an accessibility API. Valid names are: title attribute, element content.
  - WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.Button.Name
  - #cboxSlideshow
  - `<button id="cboxSlideshow"></button>`
- **Error:** This button element does not have a name available to an accessibility API. Valid names are: title attribute, element content.
  - WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.Button.Name
  - #cboxClose
  - `<button id="cboxClose"></button>`
## Summary:
- 41 Errors

**Comment by GUI** [comment]
Thanks for doing this!

So I think all of these contrast issues stem from the [Data.gov](https://www.data.gov) template we're using, so I'm unfortunately not sure we can do much about these unless we start to deviate from the Data.gov theme.

@gbinal: Do you have any thoughts on this? Or whether we should forward this onto some from the Data.gov team? (I'm not exactly sure who that would be on the design-side of things)

**Comment by gbinal** [comment]
Plan to address this in a future overhaul, but not before then.
