### ISSUE TITLE
Geo IP data invalid starting 2016-04-12

### ISSUE THREAD

**Issue by GUI** [18F/api.data.gov#327]
Starting yesterday (April 12), all of the IP geocoding appears corrupted/invalid:

![screen shot 2016-04-13 at 11 14 07 am](https://cloud.githubusercontent.com/assets/12112/14502605/4b74fbd8-0169-11e6-91b7-f4efb21c6154.png)

The last part in the "City" column, seems to correspond with the correct state (for example, "PA" in the first result), so it seems like something is shifted around incorrectly within the binary data.

In order to make sure our IP geocodes stay current, ever 24 hours, we attempt to fetch any updates to the MaxMind GeoIP database we use: http://dev.maxmind.com/geoip/legacy/geolite/ So it would appear that something is corrupted in the latest download. They are supposed to only update the data on the first Tuesday of each month, which would have been April 5, but the fact that this cropped up on a Tuesday might be relevant.

We need to see if the current downloads available from MaxMind are similarly problematic. If not, then we just need to force a new download, and then it would also be good to reprocess the IP data from the past couple days. If the current dataset is still returning corrupt results, we need to try and figure out if this is affecting all nginx users (we're using nginx's standard geoip module), and whether we can rollback to a file that still works.

**Comment by pkarman** [comment]
related: http://fusion.net/story/287592/internet-mapping-glitch-kansas-farm/

> MaxMind will refresh its database next Tuesday.

**Comment by GUI** [comment]
Well, that's a fascinating story. Poor farm!

I've confirmed that this is an issue with the latest 20160412 version of the GeoLiteCityv6.dat file. The previous 20160405 version does not behave this way. The problem is reproducible with the other MaxMind tools (like their command line `geoiplookup6` tool), so it's not just the nginx integration. There's also other people reporting the same issues this week: http://stackoverflow.com/q/36599521/222487

I reached out to MaxMind yesterday about the issue. I haven't heard anything back, but hopefully it will be fixed in their normal updates next Tuesday (or maybe sooner). Rather than disable our auto-update mechanism and try to force the installation of last week's data file, I think I'm just going to try and wait until the auto-update should hopefully resolve things next Tuesday. Then we'll need to re-process the past week's worth of data.

However, if it isn't fixed by next Tuesday by MaxMind, then I can look into how we can workaround this. We could either freeze our data file to last week's version (luckily I still have a copy of that), or we could also switch to the IPv4-only file which doesn't seem to be experiencing this same issue. Since we're not currently in an IPv6 environment, we wouldn't see any differences, but we had just defaulted API Umbrella to the IPv6 file (which also works for IPv4).

**Comment by GUI** [comment]
I heard back from MaxMind's support:

> We were able to confirm that it was indeed a corrupt file and have taken steps to correct the issue. 

The new 20160415 version of the database is in place, and geocodes are now looking correct again.

However, I still need to re-process the Tuesday-Friday traffic that now has corrupt geocoding data in it. I'll keep this issue open until I get to that.

**Comment by GUI** [comment]
The log data from this period of time has been reprocessed so the geocoded IPs are now correct for these few days (script: https://github.com/NREL/api-umbrella/commit/282861e50615e3bdb9dbf031ec6029cc15456c7c).
