### ISSUE TITLE
Investigate impact of using Let's Encrypt certificates for JVM clients

### ISSUE THREAD

**Issue by GUI** [18F/api.data.gov#329]
It came to our attention that our Let's Encrypt SSL certificate for api.data.gov may have compatibility issues with certain JVM environments, since Let's Encrypt root certificate isn't in some default JVM keystores. We need to do further analysis of our analytics to better understand the impact of this.

Based on a quick look at things on Monday, I don't see any huge drop-offs in overall traffic, and drilling down into java-based user agents doesn't reveal any huge drop-offs either. However, that's not to say it's not impacting smaller users, or it may impact users in the future (since some of our big Java users seem somewhat sporadic in their usage of APIs). HTTPS usage is also somewhat uneven on the services potentially impacted, so users using HTTP could be masking the issue as well. But at least on first glance, it doesn't seem like we've impacted many existing users with the switch, but I'd still like to dig a bit deeper.

**Comment by GUI** [comment]
Well, very belatedly, a few additional notes and updates on this:

- Aside from a couple of initial support requests when we first switched api.data.gov to use the Let's Encrypt certificate, we haven't heard of any issues from JVM users. Our analytics also don't indicate any significant drop-off in usage from JVM clients.
  - But again, it's important to caveat this with the fact that JVM users appear to be in the minority for these specific APIs that live on api.data.gov, and not all of them are using HTTPS connections. The picture could definitely be different for other APIs, so we should still probably do some analytics leg-work before migrating any other existing agency subdomains over to Let's Encrypt.
- For cases where we've rolled out brand new agency subdomains with Let's Encrypt certs, we haven't heard of any issues from JVM users. It's difficult to draw real conclusions on this, but since there's less risk for new domains (since we're not possibly breaking any existing usage), I think we'll still continue to roll out new agency subdomains with Let's Encrypt certificates unless we begin to hear from JVM users.
  - I haven't really dug into the analytics on these new domains to see what JVM usage might look like.
  - Since these are brand new domains and new API users, there are a few possibilities of what might be happening: knowledgeable JVM users are adding the cert, JVM users are disabling SSL verification after hitting problems, or JVM users are getting frustrated and leaving. I'm hoping the latter 2 events are not happening, but since we haven't had any support requests, it's a bit tough to tell.
- It's worth noting that in some quick testing, some JVM installations do seem to trust Let's Encrypt by default (for example, OpenJDK in CentOS 6), but other's do not (for example, Oracle JDK on Mac OS X). I haven't really dug into this, but it possibly means that this may not be a universal issue for all JVM users.
- It's also worth noting that the necessary root certificate is being [added to the JDK](https://bugs.openjdk.java.net/browse/JDK-8154757). It looks like it's also being backported to JVM 7. While I don't think these releases are out yet (7u111 and 8u101), my hope is that a lot of this should simply go away once these updates trickle down.
- In the meantime, I've finally added some documentation we can point JVM users to describe the issue and explain manual workarounds: http://api.data.gov/docs/https/#jvm-keystore
  - @konklone: Any thoughts on that documentation page above? I'm a little hesitant to be providing instructions about adding root certificates to the keystore, but I've tried to caveat it with enough clarification and triple-checking, so we're not encouraging users to add any certificate willy-nilly. But let us know if you don't think this is a good idea, or have any other suggestions.

**Comment by GUI** [comment]
Whoops, I didn't mean to close this quite yet without further feedback.. In any case, while the situation definitely isn't ideal for JVM API clients, with the combination of factors (lack of support requests, potential JVM updates fixing this, and manual workarounds), I'm still somewhat inclined to continue pursing the usage of Let's Encrypt for our API traffic. But give a shout if you feel differently or have any other thoughts on this.

**Comment by karlmdavis** [comment]
FWIW, this sounds like something that could use some integration tests. Do you guys have a multiplatform test environment you can use for that?

**Comment by konklone** [comment]
> In the meantime, I've finally added some documentation we can point JVM users to describe the issue and explain manual workarounds: http://api.data.gov/docs/https/#jvm-keystore

@GUI This generally looks great, especially since you're having them download it over HTTPS using `curl`, rather than plain HTTP. The one thing I'd suggest is that rather than telling users to compare the downloaded certificate to another one, I would tell them to compare the hashes, using `sha256sum` or similar.

**Comment by GUI** [comment]
@konklone: So are you suggesting we provide the expected sha256 checksum of the file they download? That certainly would be simpler (and probably less error prone), assuming they trust our page.

I had actually thought about using a checksum, but since this is a root certificate they're installing, I had sort of wanted to provide proof that this certificate really is a trusted root certificate by most systems (hence the haxx.se link and Firefox explanation). I didn't want them thinking this is just some random root certificate we're telling them to install, and encouraging that type of blind installation (since even with a checksum, we could be telling them to install some bad cert). What about providing them the checksum and verification instructions as the primary verification method, and then shifting some of the further verification steps to sub-bullet (that they can take or leave depending on how much they trust us)? Or does that extra verification from other sources seem like overkill?

Thanks!

**Comment by GUI** [comment]
@karlmdavis: Thanks for the idea! We do a lot of automated testing at the proxy layer of our stack, but we do lack a multi-platform test environment to test different types of clients in a true end-to-end fashion. I'm not sure setting something up like that is in the cards for us currently, but it's definitely a good idea we'll keep in mind. Thanks!

**Comment by tbroyer** [comment]
FWIW, OpenJDK on Debian (and probably also CentOS) uses the system certificates through a dpkg hook that generates a keystore from `/etc/ssl/certificates`. The generated keystore is simply linked from the JRE in place if the file provided in the OpenJDK sources (and used by Oracle JDK). So with an Oracle JDK on those systems you can symlink similarly.

**Comment by konklone** [comment]
@GUI Any of the above sounds good, I really am just saying that I don't think people have the capability to reliably eyeball a whole certificate and compare it to another whole certificate. Having advice to use a hash-based method in some form seems good.

**Comment by GUI** [comment]
@tbroyer: That's actually incredibly useful to know. I was curious why my CentOS boxes were behaving differently, but hadn't uncovered that tidbit. But that makes sense now. This is also another factor that may lessen the potential impact of the Let's Encrypt certs on API clients, since at least a good number of Linux+JVM distros may not be affected (and a decent number of API consumers may be linux servers). And while it's a super-small sample size, that jives with our 2 support requests being a ColdFusion+Windows environment and a Mac desktop environment. Thanks for the tip!

@konklone: Yup that sounds good. Thanks again for the feedback. I've tweaked the [instructions](http://api.data.gov/docs/https/#jvm-keystore) a bit to provide a checksum.

So with a few of these questions cleared up, and some docs to link to, I think I'm now going to close this issue (but we can always reopen if we begin to hear of further issues). Thanks to everyone for the input!
