### ISSUE TITLE
Consider auto-scaling setup for servers

### ISSUE THREAD

**Issue by GUI** [18F/api.data.gov#336]
Auto-scaling could help with general scalability and dealing with unexpected infrastructure issues.

I think we had discussed this when we rolled out the system updates last fall (or at least I had looked into it then), but it ended up being a bit too much to bite off at the time with all the other updates going on. But we did take some steps during that rollout that should help if we want to tackle this, since our base system stuff is now better automated through Cloud Formation. However, there are still a number of things we'd need to figure out:
- Outgoing IPs: We need to have static outgoing IPs, since agencies frequently use our IPs to whitelist traffic to their API backends. We could solve this by shifting our static IPs to NAT servers, and routing all our outbound traffic through those, but that makes our infrastructure more complicated in other ways (since then we need to worry about the availability of these NAT servers too).
- Pre-baking AMIs: To make auto-scaling more responsive, I think we'd need to pre-bake AMIs with our API Umbrella installation on them. Or explore things like Docker containers. In either case, we'd have to figure out our deployment process with this type of setup, since we currently install from our binary packages, but then periodically do live deployments of the latest code from git master on top of those installations.
- Making our servers truly ephemeral: Our application servers are pretty disposable, but we'd probably need to implement centralized logging for system/process logs so we could really destroy the machines on a whim and not worry about anything (https://github.com/18F/api.data.gov/issues/337).

**Comment by gbinal** [comment]
This will be mitigated by cloud.gov, so I'm going to close it in favor of that effort.
