### ISSUE TITLE
Centralized logging for system/process logs

### ISSUE THREAD

**Issue by GUI** [18F/api.data.gov#337]
We funnel all of our analytics logs off to a centralized database, but we may also want to consider a solution for centralizing our other types of system and process log files. This would help mitigate the possibility of lots of log data filling up our proxy servers and impacting service (https://github.com/18F/api.data.gov/issues/333), and would also help make our proxy servers more disposable (which would be relevant for auto-scaling: https://github.com/18F/api.data.gov/issues/336).

**Comment by gbinal** [comment]
Moving to cloud.gov fully will address this so that'll be our priority.
