### ISSUE TITLE
Remove Log In link from footer?

### ISSUE THREAD

**Issue by GUI** [18F/api.data.gov#338]
Someone pointed out today that there's a "Log In" link in the footer of https://api.data.gov. However, this links to the Data.gov catalog login, rather than anything related to api.data.gov. This is actually the second person that I think has hit this recently (I just hadn't realized the first time that the other person likely landed on it by following that same link on the home page).

If it sounds okay to deviate slightly from the Data.gov theme, I think it might be more intuitive to remove this link or change it to our admin link.

**Comment by gbinal** [comment]
Totally agree.  Let's change it to ours.

**Comment by GUI** [comment]
👍 Okay, it's switch to link to our admin.
