### ISSUE TITLE
Add link to metrics page?

### ISSUE THREAD

**Issue by GUI** [18F/api.data.gov#340]
We have our public metrics page at http://api.data.gov/metrics/, but I don't think we actually link to it anywhere. I think it would be useful to share this page more broadly, since we do get questions about this periodically.

Should we maybe put a link to it on the home page somewhere under the "About This Service" section? Or any other preferences or ideas on where to put this?

**Comment by gbinal** [comment]
Sure.  I'm game for wherever.

**Comment by gbinal** [comment]
I'm going to go ahead and close this.  I directly point people to it from time to time and anything further can hold on a further rethinking of the site itself.
