### ISSUE TITLE
typo in api error message 

### ISSUE THREAD

**Issue by gbinal** [18F/api.data.gov#347]
Using the college scorecard API, one sees this error message:  

````
{
  "error": {
    "code": "<h1>API KEY MISSING</h1>",
    "message": "<hr>College Scorecard requires an API Key for access. <br><br>To obtain a key, visit <a href=\"https://api.data.gov/signup\">https://api.data.gov/signup</a>.<br><br> You will receive an email with your key. When you receive this key, simply append it to your API requestions with the additional parameter &api_key=xxxxxxxxxxxxx."
  }
````

`requestions` should be `requests`

**Comment by GUI** [comment]
This should be fixed now (although I sort of like the "requestions" mashup word ;).

For future reference, if else wants to tweak the wording, this can be edited the API Backend admin. Within the College Scorecard backend, this message is customized in the Advanced Settings > Error Data section.
