### ISSUE TITLE
Add support of wildcard hosts in the admin scoping permissions

### ISSUE THREAD

**Issue by GUI** [18F/api.data.gov#349]
In the admin permissions system, we have a concept of API Scopes which define which host and which path the admin user has access to. So, for example, this is how I could define an API Scope of `developer.nrel.gov/` to grant access to all developer.nrel.gov related things, or I could create a more specific scope of `developer.nrel.gov/api/pvwatts` to only grant access on certain sub-paths.

The path portion of the API Scope sort of acts like a wildcard, since it's a path _prefix_ (so `/` will match anything starting with `/` which is everything). However, there's currently no way to make the host portion of the API Scope a wildcard pattern. We support wildcard hosts in other parts of the system, so think it would be good to add support for wildcard hosts in the API Scope section (both a global wildcard like `*`, as well as subdomain wildcards like `*.api.example.com`).

The primary use-case for this that just came up was setting up a global analytics-only account. If we added support wildcard hosts, then this could just be a a single API Scope for any host and any path. We then wouldn't have to worry about this account getting access to new hosts as we add them to the system (since new hosts would always be covered by the wildcard match).

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
