### ISSUE TITLE
Determine why cached responses aren't persisting as long as they should in some cases

### ISSUE THREAD

**Issue by GUI** [18F/api.data.gov#352]
This is related to an issue impacting NREL APIs I've been debugging, but I think I've tracked it down to a potential issue with api.data.gov's caching layer not behaving as expected. The short version is that I believe the HTTP caching layer for api.data.gov was sized far too small, which was causing cache invalidations to happen much more frequently than expected. I've tried increasing the cache storage size, but it might take a few days of running to see if this resolves the periodic issues we were seeing with our NREL APIs.

For a bit more detail:

We have an API at NREL that returns a response body that's a tad bigger than normal (2.5MB of compressed JSON or 15MB uncompressed). This API also happens to take a bit more time & CPU resources for our server to generate. To alleviate the load on our API server when this API gets hit repeatedly, we added Cache-Control headers on this API to let API Umbrella cache the response for up to 5 minutes (the data changes semi-frequently, so we didn't want to cache it for super-long). We added those headers ages ago, and while it perhaps wasn't a perfect solution, it was a quick and easy solution that mitigated the server load issues we were seeing.

With api.data.gov providing the caching for this API endpoint, our underlying API servers should see at most 2 requests every 5 minutes for this endpoint (since we have 2 separate api.data.gov caching servers with a 5 minute TTL). For any other identical requests received within a 5 minute window, the HTTP cache should be returning cached responses. Even if a bunch of identical requests come in for an uncached object at the same time, we have explicitly setup the API Umbrella's caching component to try and avoid [thundering herd issues](https://docs.trafficserver.apache.org/en/5.3.x/admin/http-proxy-caching.en.html#reducing-origin-server-requests-avoiding-the-thundering-herd) that would result in lots of backend requests.

For the past few weeks, though, we've been seeing really random server load spikes on some of NREL's API servers that have been impacting our APIs. I believe I've finally tracked the issue to periodic surges our API backend servers were receiving for these specific APIs that are more resource-intensive, but should be cached. The puzzling part of this was that during these surges, our API backend was receiving far more requests for identical URLs than the cache should have allowed. For example, last night our API backend received around 500 requests within 30 minutes for the exact same URL, far exceeding the 2 requests per 5 minutes that should occur with the cache in front.

At first I thought the requests might be busting the cache somehow, but the requests all appeared woefully normal. Then, I thought the thundering herd/connection collapsing from the cache server might not be working properly, but the requests weren't even that close in time (and while TrafficServer 5.3's collapsing might not be 100% perfect in all situations, we do a fair bit of testing to ensure that it basically works as intended).

Then I stumbled upon the fact that we've configured API Umbrella with a woefully small default disk cache size for TrafficServer at only 256MB, and we've never adjusted that for api.data.gov's setup. Eek! So I believe what was happening is that the disk cache was utterly starved for space, which resulted in any cacheable response fighting for space with other cacheable responses. I think this was leading to rather unpredictable caching behavior, with cached responses being forced out of cache storage nearly immediately. Thin in turn, could lead to random bursts of requests to the API backend being let through if the cacheable responses were never really persisting in the cache.

So to hopefully fix this, I've simply allocated more disk space to TrafficServer's cache (6GB), and more to TrafficServer's RAM cache too (2GB): https://github.com/18F/api.data.gov-ops/commit/840fba9e060ac8836335685170f907ade2b79554 At this point, I'm not 100% sure this is the culprit, but it seems to make sense and would seem to explain the strange behavior we were seeing on the NREL APIs (and in any case, the cache was woefully under-tuned). Since the issues we were seeing at NREL were somewhat sporadic, we might have to wait a few days to see if they crop up again, but based on the last few hours of running, things do appear better behaved and api.data.gov's cache metrics are looking better.

If this does fix the issue, we may also want to consider bumping the cache storage size in API Umbrella's [default config](https://github.com/NREL/api-umbrella/blob/v0.13.0/config/default.yml#L66-L67). While I think it's okay to be conservative with our defaults and just document how to raise it if needed, it seems like we could still stand to raise the default disk and RAM cache sizes a bit.

**Comment by gbinal** [comment]
It seems that this has been addressed by intervening efforts.  I'm going to go ahead and close it.
