### ISSUE TITLE
Examples and API Keys don't work

### ISSUE THREAD

**Issue by cantrowitz** [18F/api.data.gov#353]
I tried to access the examples at the bottom of this page:
https://ndb.nal.usda.gov/ndb/doc/apilist/API-SEARCH.md

Namely http://api.nal.usda.gov/ndb/search/?format=xml&q=butter&max=25&offset=0&api_key=DEMO_KEY

But I get an error message with the following error:
Please contact us for assistance: https://api.data.gov/contact/ or https://github.com/18F/api.data.gov/issues

I get the same error with JSON as XML.

**Comment by gbinal** [comment]
It looks like this issue resolved itself.  The example return is resolving successsfully.  I'm going to go ahead and close.
