### ISSUE TITLE
api analytics drilldown errors

### ISSUE THREAD

**Issue by PaulClark2** [18F/api.data.gov#356]
I generally have problems with the analytics tool. It often does not return answers to queries.

I received this error message when I selected analytics-->api drilldown
![api data gov-unexpected-error](https://cloud.githubusercontent.com/assets/11817734/19117978/ead814d6-8ae8-11e6-9cda-6ab0bc3585ea.png)

I received this error when I tried to query a custom date range
![api data gov-datatables-error](https://cloud.githubusercontent.com/assets/11817734/19118010/02ef4cba-8ae9-11e6-9edd-27232966d33a.png)

**Comment by ccostino** [comment]
To add to this issue, it seems that the responses are all timing out no matter which Analytics feature you go to (API Drilldown, Filter logs, By User, and By Location).  I am seeing 504 errors being returned for all of the Ajax/XHR requests.

**Comment by GUI** [comment]
Sorry about this!

Things should be back in action, but the caveat is that you unfortunately can't query more than probably 3-6 months of data at a time. So if you're looking for longer historical data, you'll sadly need to sort of piece that together from multiple queries.

Sorry for the inconvenience if you're looking to pull longer historical data. We have some improvements in the pipeline that should hopefully address this, but we need to circle back to wrap some things up (https://github.com/18F/api.data.gov/issues/235). In the meantime, if you're looking for specific queries over longer periods of time, then also free to reach out, and we can see about pulling the data manually for you.

**Comment by ccostino** [comment]
Great, thank you @GUI for looking into this and providing a bit more background on the current constraints!

**Comment by PaulClark2** [comment]
Hi, @GUI I'd like to take up on your offer to run a query over a longer period of time.  Can I get the number of hits on api.open.fec.gov/ between July 2015 and today?  Thanks!

I just need a top line number like the one in the image below but for hits between July 2015 and today.
![untitled](https://cloud.githubusercontent.com/assets/11817734/19530157/ad97f4b0-9600-11e6-8bde-8601bba4ce7b.png)

**Comment by GUI** [comment]
@PaulClark2: Apologies for the delay, you should have e-mail with stats.

**Comment by gbinal** [comment]
We addressed this by increasing the size of the servers and plan to further get ahead by updating the software powering this section.  I'm going to go ahead and close this for now.
