### ISSUE TITLE
Re-write the default API key language 

### ISSUE THREAD

**Issue by gbinal** [18F/api.data.gov#359]
There's a few changes I'd like to make to this blurb.  Once we do, though, we should re-engage existing users to spread it further.  

![screen shot 2016-11-04 at 1 25 50 pm](https://cloud.githubusercontent.com/assets/633088/20015564/51b3e49e-a292-11e6-9e96-cf668261f910.png)

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
