### ISSUE TITLE
Migrate off of GitHub Pages for webpage hosting

### ISSUE THREAD

**Issue by GUI** [18F/api.data.gov#365]
Currently api.data.gov's static web page content is using GitHub Pages for hosting (which we proxy to). I think I remember hearing at some point that GitHub Pages should not be used for 18F projects, but we should confirm. If that's the case, then we need to plunk this content some place else for hosting. There's not much to our site and it doesn't change very often, so our needs are pretty basic. An S3 bucket or Federalist would do the trick.

**Comment by gbinal** [comment]
I'm investigating but don't worry about this in the meantime.

**Comment by monfresh** [comment]
Hello. Any updates on this issue? As I'm sure you're aware, migrating off of GitHub pages is a requirement for obtaining your ATO.

**Comment by gbinal** [comment]
Yep - all good.  We were discussing earlier this week.  It's on our plans for the near future.
