### ISSUE TITLE
How do I create API Keys for other users?

### ISSUE THREAD

**Issue by SamuelKnox** [18F/api.data.gov#367]
Stack Exchange Question:

http://opendata.stackexchange.com/questions/10454/how-can-i-register-a-new-api-key-for-api-data-gov-programatically

api.data.gov allows for up to 1,000 API requests per user per hour, which is plenty. However, each user requires their own API Key. How can I request a key for them without asking a user to register with api.data.gov?

The API I am using says:

"If you engineer your app to request a key for each user during your registration process – all they need is the users’ email, the app then acquires a key and stores it for use by the app. This then gives each instance of the app a rate limit of 1000/hr."
But they do not say how to create a key for those users.

The underlying technology is API Umbrella, but their documentation is not clear to me in programatically generating a key for users either.

How can I create a new key for each of my users, which could number in the thousands?

**Comment by GUI** [comment]
api.data.gov doesn't actually support end users programmatically creating API keys at this time. Sorry for the mixup. We'll followup in more detail with you and the USDA team via email about potential alternatives for higher rate limits.
