### ISSUE TITLE
Contact form problem

### ISSUE THREAD

**Issue by suscodev** [18F/api.data.gov#371]
Hi,

I've tried to reach out about rate limits for the OpenEI utility rate lookup API using https://api.data.gov/contact/. The page hangs when the <Send> button is clicked.

So, 
1. the <Send> button on https://api.data.gov/contact/ has a problem, and 
2. are there any options available for raising the request limit for a once-monthly batch?

***UPDATE 20170307:
The original issue occurred using Chrome on Windows 10. Both Edge and Firefox on Windows 10 show the same problem. No error arises; the screen just remains grayed out as though it's waiting for a modal to pop up, but the browsers don't show any notifications about blocked popups.
***UPDATE 20170307

Thanks-
-Mary Reiner
SuscoDev

**Comment by GUI** [comment]
Thanks for reporting the issue with the contact form. We'll look into it.

In the meantime, we have received your messages (despite the contact form not showing you a confirmation). We've forwarded them onto the OpenEI team, so hopefully they'll be in touch. If you haven't heard back, you might also try reaching out to the OpenEI team directly at openei.webmaster@nrel.gov or http://en.openei.org/community/group/developer

**Comment by suscodev** [comment]
Nick, so sorry to have spammed you! Thanks for the confirmation and for the direct contact info.

-Mary

Mary D. Reiner
Sr. Application Developer
Susco & Touch Studios
(504) 264-9343
http://suscotouch.com

**Comment by GUI** [comment]
Well, rather belated, but the contact form should now be fixed so you receive a confirmation message after a successful send. Thanks for the heads up about the issue!

**Comment by suscodev** [comment]
Awesome; thanks!
