### ISSUE TITLE
set up protected branches

### ISSUE THREAD

**Issue by gbinal** [18F/api.data.gov#373]
For https://github.com/18F/api.data.gov and https://github.com/nrel/api-umbrella, we need to [protect the master branches](https://help.github.com/articles/defining-the-mergeability-of-pull-requests/).  

@gui - do you see this causing any issues with that for either repo?  If not, can you do for the nrel repo?

**Comment by GUI** [comment]
Nope, I don't see any issues. `master` was already setup as a protected branch on NREL/api-umbrella. I went ahead and added `master` as a protected branch on 18F/api.data.gov. So both should now be setup as protected branches preventing forced pushes (but let me know if you had in mind enabling some of the other protection features like requiring pull request approvals, etc).

**Comment by GUI** [comment]
Whoops, look like we did this last year, but then I forgot to close this issue. Closing now.
