### ISSUE TITLE
What do we need to know about moving to Cloud.gov?

### ISSUE THREAD

**Issue by sashax** [18F/api.data.gov#386]
- What about Latency?
- Does it support MongoDB?
- What version of Elasticsearch?

**Comment by sashax** [comment]
- What about Latency?
- Does it support MongoDB?
-- it does not at the moment. It can be exposed, particularly if it's done as a temporary migration aid, but they're not eager to do so.
- What version of Elasticsearch?
-- currently 2.4. They can upgrade to 5.4 if we need it. However, they only support a single instance of Elasticsearch, which may not work for us. 

Note that one possible advantage of hosting api.data.gov on cloud.gov is that we could build a broker for the service which'd allow us to easily serve APIs on the service. 

See: https://docs.cloudfoundry.org/services/overview.html

**Comment by gbinal** [comment]
This remains in the indefinite future, so I'm going to close for now.
