### ISSUE TITLE
API rate limits 1000 per hour per IP or not

### ISSUE THREAD

**Issue by SteveCEms** [18F/api.data.gov#388]
On this page api.data.gov/docs/rate-limits/, I see this rate limit:
Hourly Limit: 1,000 requests per hour.
While on this page
ndb.nal.usda.gov/ndb/api/doc, I see this rate limit:
We currently limit the number of API requests to a default rate of 1,000 requests per hour per IP address.

What is the rate limit?

**Comment by gbinal** [comment]
HI @SteveCEms.  The information on api.data.gov/docs/rate-limits is a default for agencies that employ this service, however each agency is able to further modify these settings to suite their needs.  In the case of the NDB api, you should rely on their documentation.  

Thanks for getting in touch.
