### ISSUE TITLE
"Vary: Origin" header not affecting cache as expected

### ISSUE THREAD

**Issue by GUI** [18F/api.data.gov#397]
This was brought to our attention here: https://github.com/NREL/developer.nrel.gov/issues/67 It looks like the same cached responses are getting returned for different `Origin` HTTP header values, despite the API's response containing a `Vary: Origin` header. In other words, the cached response is being returned in situations where it should not be, so we need to investigate this to figure out where the problem lies.

For more detail:

NREL has an API that adjusts the `Access-Control-Allow-Origin` HTTP header based on the incoming `Origin` values. So, for example:

- If you make the API request with a request header value of `Origin: http://1.example.com`, then the response should have a header value of `Access-Control-Allow-Origin: http://1.example.com`.
- If another request comes in with `Origin: http://2.example.com`, then its response header should be `Access-Control-Allow-Origin: http://2.example.com`.

For these specific responses, our response also contains a `Surrogate-Control` header to allow the api.data.gov caching layer to cache the responses. But what's happening is that the the first response back gets cached and then gets returned to all subsequent requests, regardless of their `Origin` value (until the cache expires). So this means, you might get back a response without the expected `Access-Control-Allow-Origin` value if the same URL was previously hit and cached.

The first response getting cached would be expected, but the API response also contains a `Vary: Origin` HTTP header. This should instruct the HTTP caching layer to keep the cache's separate depending on the request's `Origin` header (so the `Origin: http://1.example.com` request and `Origin: http://2.example.com` would both get cached, but would only be returned for requests that match the same Origin value).

On the NREL side of things, I'm not actually sure why this API is handling the CORS response headers in this way (it seems to be a default behavior of the rack-cors gem), so I think we can potentially sidestep this issue altogether by returning a static `Access-Control-Allow-Origin: *` value, and removing the `Vary: Origin` header.

However, this would be good to get to the bottom of, since it seems like the `Vary` header is perhaps not working with the caching layer expected. We have [test coverage](https://github.com/NREL/api-umbrella/blob/master/test/proxy/caching/test_vary.rb) to check the behavior of the cache and Vary support, so I think the basics are working. But I'm wondering if somehow the combination of `Surrogate-Control` breaks things, or if something else might be at play (either specific to `Origin`, or something else I'm missing).

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
