### ISSUE TITLE
UI issue for rate limits

### ISSUE THREAD

**Issue by LindsayYoung** [18F/api.data.gov#399]
Recently, we ran into an issue with the FEC API where we needed to change a custom rate limit to unlimited rate limit. On saving there is  an error at the top of the page because you need to remove the custom limit before applying the unlimited rule, but I missed it. I retraced my steps later and figured out my user error. It would be nice it the error was more in your face.

Thanks again!

**Comment by GUI** [comment]
Well, I'd argue that's more of an application bug rather than user error. :) The app should be smart enough to clear any custom limits if you're explicitly switching away from that mode. Sorry for the trouble, but thanks for reporting the issue. We'll look to get this fixed.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
