### ISSUE TITLE
How to test FCC API submissions without making actual submissions

### ISSUE THREAD

**Issue by wkw** [18F/api.data.gov#403]
We are interested in exploring the FCC API, but the docs do not indicate any way to test our integration in a sandbox or test environment. Does the `DEMO_KEY` as mentioned [here](https://api.data.gov/docs/rate-limits/) imply no data is submitted? Are there API flags that can be used to say "test transaction"?

**Comment by pablojmarti** [comment]
+1

**Comment by GUI** [comment]
The FCC ECFS API uses api.data.gov's service for API key functionality, but for these kind of specific API questions or feedback, we're unfortunately not the best point of contact. I'd recommend reaching out to the FCC directly at ECFSHelp@fcc.gov about this ability to send test transactions to this API.

Although, regarding the `DEMO_KEY`, I can at least answer that part: Using `DEMO_KEY` will still make real API requests (it just has much lower rate limits), so I don't think that's what you're looking for.

Hope that helps, but let us know if you have any further questions.
