### ISSUE TITLE
api analytics drilldown errors

### ISSUE THREAD

**Issue by PaulClark2** [18F/api.data.gov#405]
I'm trying to get a top line hits number like the one in the image below but for all of FY 2017 (10/01/2016 to 09/30/2017). 
![image](https://user-images.githubusercontent.com/11817734/32344255-99aefb4a-bfdc-11e7-8330-af85115b6647.png)

However, I received this error when I tried to query using a custom date range.
![image](https://user-images.githubusercontent.com/11817734/32344136-2d84e772-bfdc-11e7-9218-7628c0cdde63.png)

**Comment by gbinal** [comment]
Hi @PaulClark2 - 

We're investigating this to confirm, but our suspicion is that the overall volume of the hits being processed in this query is causing the error.  I know that it's unsatisfying but just to check, are you able to find the results you need in 4 or 6 month chunks instead of 12?

**Comment by PaulClark2** [comment]
Hi, @gbinal. I haven't tried pulling the counts in smaller chunks. I can give that a try.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
