### ISSUE TITLE
CSV download for admin drilldown analytics not working

### ISSUE THREAD

**Issue by GUI** [18F/api.data.gov#410]
In the admin tool, the CSV downloads in the Analytics > API Drilldown section aren't working. Clicking on the CSV download results in a forbidden error.

I suspect this became broken in this commit: https://github.com/NREL/api-umbrella/commit/89371149585c1c94d1420bd8ce190a6fcdadb59b This changed how we pass the admin session to API backends (defaulting to stripping the admin session cookie), which I think it affecting this CSV download link.

**Comment by GUI** [comment]
Fixed by https://github.com/NREL/api-umbrella/commit/d24e4a3602525e15b2086a98b73c7343d78e38e2

(cc @gbinal: This should fix at least part of what you were trying to pull last week)

**Comment by gbinal** [comment]
Sounds good - thanks!
