### ISSUE TITLE
Additional Filter: Custom Rate Limits

### ISSUE THREAD

**Issue by brownpl** [18F/api.data.gov#414]
In the API Admin dashboard, it would be great to have an option to filter users by those that have custom API rates set. I periodically like to review them and adjust as appropriate, and currently I need to keep a secondary list to be able to track everyone down.

**Comment by GUI** [comment]
A very belated response, but I do think this is a good idea and something we'd like to do. There was already an existing issue about this in https://github.com/18F/api.data.gov/issues/171, so I'm going to close this one just to tidy things up.
