### ISSUE TITLE
Red notices for api-umbrella in gemnasium.

### ISSUE THREAD

**Issue by gbinal** [18F/api.data.gov#418]
There are two red notices for https://gemnasium.com/github.com/NREL/api-umbrella in gemnasium.  Investigating.

**Comment by gbinal** [comment]
It looks like neither of the alerts likely affect us, but we should still update them in any case.

**Comment by GUI** [comment]
Updated moment.js: https://github.com/NREL/api-umbrella/commit/6a97a23bb677ba5b45bdf4376fe7f9f789615c7a

For the `ws` dependency, we can't easily update (it's a dependency of a dependency of a dependency), but it's only used (if at all) in development, so it shouldn't actually pose any security issue to the app.
