### ISSUE TITLE
Ensure HTTPS-compliance via Pulse

### ISSUE THREAD

**Issue by gbinal** [18F/api.data.gov#422]
On https://pulse.cio.gov/https/domains/#q=data.gov, when looking at api.data.gov: 

It looks like we need to deprecate 3DES.

**Comment by GUI** [comment]
The 3DES ciphers are now disabled. So I think we should be good, but I'll wait to close this issue until Pulse run agains tonight just to double check things.

**Comment by gbinal** [comment]
The Pulse report is looking good (image below).  I'm going to go ahead and close.  

![screen shot 2018-01-18 at 1 40 50 pm](https://user-images.githubusercontent.com/633088/35115181-557e4560-fc55-11e7-8206-4ac74f2ef3f4.png)
