### ISSUE TITLE
Update jQuery version

### ISSUE THREAD

**Issue by gbinal** [18F/api.data.gov#423]
Location: https://api.data.gov/static/javascripts/signup_embed.js

Recommendation: Upgrade the vulnerable library to the latest version or the library version
3.0.0-beta1 at minimum. This vulnerability is affecting all versions of the library prior to 3.0.0-
beta1 (between 1.12.3 and 3.0.0-beta1).

**Comment by GUI** [comment]
@gbinal: Updated to jQuery 3.2.1 (https://github.com/18F/api.data.gov/commit/c522afd7966fcd120acb30e21ea6ade2aa8a1d91), so this should be resolved.
