### ISSUE TITLE
Evaluate TLS version requirements from API clients

### ISSUE THREAD

**Issue by GUI** [18F/api.data.gov#436]
The current SSL setup we provide enables TLS v1.0, v1.1, and v1.2 by default. We've had a request from an agency to disable everything except v1.2. We now have a setup (using a separate ELB with SNI) that we can switch specific agency subdomains to that also want TLS v1.2 only. However, this has brought up the fact that we should probably evaluate the TLS versions across all our existing agency subdomains and our default setup.

I realize Cloud.gov has [recently disabled TLS v1.0 and v1.1 by default](https://cloud.gov/updates/2018-03-14-tls-10-and-11-support-deprecated-drupal-8-made-easy-and-platform-updates/), however API clients tend to be a bit different from browser usage when it comes to stuff like this. So before making a wider switch, I'd like to evaluate our traffic to better understand what TLS versions API clients are currently using. To that end, I've enabled additional logging on our servers to log the protocol of each connection (along with ciphers used and ciphers supported, since those could also be interesting to analyze). This logging is now enabled, so I'd like to let this run for a while to collect data, and then we can analyze it to see what type of impact this would have across our other agency domains.

**Comment by GUI** [comment]
I was just looking into this again and pulled some quick summary stats from the data we've been logging. These stats are only from the past 6 days, but we could dig into the older log files if we want to stretch back further:

- Non-SSL: 8.437%
- TLSv1: 8.627%
- TLSv1.1: 0.006%
- TLSv1.2: 82.930%

These numbers cover all agency domains, but we could also break this down per agency domain, since some agencies seem to have very different usage (eg, we've switched some agencies over to v1.2-only that had nearly no v1 or v1.1 requests).

The non-SSL connections are also a separate issue we should probably dig into at some point. While some of these might just represent redirects or the errors we return for non-HTTPS connections (the default for any new APIs), we still have some agencies with legacy API setups that haven't fully transitioned to enforcing HTTPS (we have tools to help agencies migrated toward this, but it requires some active work to reach out to users if you don't want to break things: https://github.com/18F/api.data.gov/issues/34).

**Comment by gbinal** [comment]
Two things come to mind on this for next steps.  
* First, figure out which agency APIs and which API keys are generating the TLSv1 hits.  
* Then, let's engage them directly to warn them about the need to change how they are hitting us.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
