### ISSUE TITLE
Better dogfood other TTS offerings

### ISSUE THREAD

**Issue by gbinal** [18F/api.data.gov#440]
We're at a point where it makes lots of sense for us to better dogfood the other offerings of TTS.  Namely:

* [ ] Login.gov for https://api.data.gov/admin
* [ ] Federalist for https://api.data.gov
* [ ] The USWDS for https://api.data.gov
* [ ] Cloud.gov for api.data.gov
* [x] The TTS Bug Bounty for api.data.gov
* [ ] What else am I forgetting... ?

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
