### ISSUE TITLE
Agency admins can't access their personal admin account page

### ISSUE THREAD

**Issue by GUI** [18F/api.data.gov#443]
Since we've removed the ability for agency admins to manage other admin accounts, this has inadvertently broken the "My Account" link in the admin where they could view and manage their account. While they won't really be able to manage their own account anymore, we need to restore some sort of basic read-only view for their own account so that they can view their Admin API Token, that was previously available on this page (otherwise, there's no other place for them to find this token).

**Comment by GUI** [comment]
Also reported https://github.com/18F/api.data.gov/issues/451

**Comment by gbinal** [comment]
Closing as a duplicate
