### ISSUE TITLE
Error when clicking "My Account" link

### ISSUE THREAD

**Issue by froi** [18F/api.data.gov#451]
**Current Behaviour**

When clicking the `My Account` link found in the top right gear menu I get an "unexpected error" message. I'm logged in using the __Sign in With Google__ option using my GSA account.

Screenshots:

![image](https://user-images.githubusercontent.com/1918027/43166826-af831dbc-8f65-11e8-9652-b9e189a74442.png)

![image](https://user-images.githubusercontent.com/1918027/43166946-14b3655c-8f66-11e8-950d-0df757f882d4.png)

Browser console error:
![image](https://user-images.githubusercontent.com/1918027/43166963-25cef4c8-8f66-11e8-83a8-26a6005e32cc.png)

Hitting __try again__ link sends me to the last screen I was on.

**Expected Behaviour**

When clicking the `My Account` link found in the top right gear menu I expect to see the settings for my account. At the very least a more clear error description stating if there is a problem with permissions or other account related issues.

**Steps to Reproduce**

1. Log in using the __Sign in With Google__ option
2. Open gear menu
3. Click on __My Account__ menu option

**Possible Solutions**

* Perhaps it's a role or permission issue with my account. I would probably check there first just to rule it out.
* No idea of any other possible solution.

**Browsers**

* Firefox: version 61.0.1 (64-bit)
* Chrome: version 68.0.3440.75 (Official Build) (64-bit)

**Comment by froi** [comment]
The Chrome dev console gives me better information on this. The response is a __403__

![image](https://user-images.githubusercontent.com/1918027/43167551-1783ad58-8f68-11e8-8a15-045be21f2f0a.png)

So I'm guessing that it's a permissions issue?

Thanks.

**Comment by GUI** [comment]
@froi: Apologies for the very belated response, but thanks for pointing this out. This issue should now be resolved, but let us know if you're still seeing any issues.

**Comment by froi** [comment]
No worries. The issues has been resolved. Thanks.
