### ISSUE TITLE
Consider reforms to api.data.gov/contact

### ISSUE THREAD

**Issue by gbinal** [18F/api.data.gov#466]
On https://api.data.gov/contact, consider: 
* revising the dropdown menu
* requiring an affirmative link click in a followup email for the message to go through.

**Comment by gbinal** [comment]
the dropdown menu could still stand to be updated, but the latter isn't necessary.  Instead, I should memorialize our workflows of only sending to the email address that registered the key.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
