### ISSUE TITLE
Weigh an overhaul of the api.data.gov website

### ISSUE THREAD

**Issue by gbinal** [18F/api.data.gov#475]
Given my thoughts in recent months about what an api.gov might look like, I wonder about instead pouring that into a redo of api.data.gov, making the shared service itself a part of that site instead of the whole focus and otherwise allowing the rest of the site to serve as 'the hub of federal APIs' that I imagine.

**Comment by gbinal** [comment]
Incorporate #164

**Comment by gbinal** [comment]
Consider creating a design system, a la uswds.

**Comment by gbinal** [comment]
Major sections:
Everything you’re looking for:
* list of APIs
* which ones use our service
* metrics
* why use our service 
* how to start using our service
* resources and guides for agencies
* how to think about the paradigm shift
* maturity model
* what else?

**Comment by gbinal** [comment]
We've got the metrics now, with api.data.gov/metrics.  

Next, I think we need to pull in the list of APIs/developer hubs.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
