### ISSUE TITLE
Error Message Outputting Viewable Markup

### ISSUE THREAD

**Issue by jalbertbowden** [18F/api.data.gov#479]
error message for bad api calls outputs html that is visible, as seen here:
https://api.data.gov/ed/collegescorecard/v1/schools?api_key=&fields=student.enrollment.all,school.name&school.state=AL
![Screenshot of Error Message](https://user-images.githubusercontent.com/46432/49944833-67485a80-feb9-11e8-9882-f01cf12e81c5.png) and [originally filed here](https://github.com/GSA/data.gov/issues/861).

**Comment by GUI** [comment]
@jalbertbowden: This HTML formatting should no longer be showing up. Thanks for the heads up!

(And just to link the issues together, also reported here: https://github.com/18F/api.data.gov/issues/366)

**Comment by jalbertbowden** [comment]
nice!
