### ISSUE TITLE
error message when trying to pull very large time periods

### ISSUE THREAD

**Issue by gbinal** [18F/api.data.gov#491]
When trying to pull analytics for a period of 2013-current day, this message appears.  I know we've faced this before but any thoughts on how to redress?  

<img width="1226" alt="Screen Shot 2019-03-12 at 3 33 37 PM" src="https://user-images.githubusercontent.com/633088/54230288-7cdf1780-44dc-11e9-80a2-e16cda3d9e0b.png">

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
