### ISSUE TITLE
API backend confirmation message is sometimes incorrect

### ISSUE THREAD

**Issue by gbinal** [18F/api.data.gov#495]
First off, great call with #494.  That was totally the right move.  

I've noticed that when I make semantic edits to API backends like changing their name or the agency/status metadata field, this message still pops up:  

![Screen Shot 2019-04-15 at 11 27 36 AM](https://user-images.githubusercontent.com/633088/56156289-cb675200-5f71-11e9-8fb7-86351034c8df.png)

It's not at all grave and since 99% of the time, the only people affected will be superadmins like us, we don't need to prioritize a fix for this.  It's just worth noting in case there's ever an easy fix.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
