### ISSUE TITLE
Fix "contactUrl" option for signup form not working for certain external sites

### ISSUE THREAD

**Issue by GUI** [18F/api.data.gov#497]
As a result of the changes made in https://github.com/18F/api.data.gov/issues/460#issuecomment-435258248, we sanitize the `contactUrl` setting used in the API key signup form against known API and website URLs. However, this has broken some agencies that were previously linking to things like the github.com issue tracker. In those cases, it's replacing the contact link with our default api.data.gov contact page, so there's still a link, but we want to ensure users are getting routed to the appropriate place for the agency. So we need some other way to whitelist other valid contact URLs beyond just URLs known to our system.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
