### ISSUE TITLE
Think through possible issues with new metrics endpoint/page

### ISSUE THREAD

**Issue by gbinal** [18F/api.data.gov#503]
Possible issues to think through and address before releasing this:  

* [ ] ~Some suspicious bumps in the the total users numbers from the last year~ That isn't urgent.  
* [x] Different formats for month/year in the json
* [x] ~Should I be OCD about the json file ordering and such?~  No, that's how json works.  
* [x] Should we add in backend url counts by organization?
* [x] Should we add in api backend counts by organization?
* [ ] Why isn't there more difference between the unique keys used vs. total keys registered?  

* [ ] How should we handle domains that we migrated (e.g. off of api.data.gov onto their own domain)?

What else?

**Comment by gbinal** [comment]
Add a link to the endpoint itself

**Comment by gbinal** [comment]
* If we phase out the old metrics page, we aren't 'getting credit' for the hits that are associated with backends that have been deleted.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
