### ISSUE TITLE
URL wrapping issues in admin analytics popups

### ISSUE THREAD

**Issue by GUI** [18F/api.data.gov#505]
This has been happening for a little while now, but I keep forgetting to fix this or file an issue: After some of the admin interface upgrades a while ago, the popover displaying the full URL in the Analytics > Filters Logs table has some wrapping issues with long URLs. See screnshot where you can see the the full URL flows outside the popover container and overlaps other text  in the table.

![Screen_Shot_2019-05-16_at_2_53_36_PM](https://user-images.githubusercontent.com/12112/57886603-cdc80080-77ea-11e9-9243-69d8b40da412.png)

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
