### ISSUE TITLE
How to login if already signed up?

### ISSUE THREAD

**Issue by s2t2** [18F/api.data.gov#509]
Expecting this page to have a link for where I can login, if I've already signed up.

https://github.com/18F/api.data.gov/blob/master/source/index.html.erb

**Comment by s2t2** [comment]
EDIT: oh the API key is sent via email? Maybe consider using a more secure management system for API keys - one which allows key regeneration.

**Comment by gbinal** [comment]
Thanks for the feedback, @s2t2 and sorry for the confusion.  The confirmation language that appears after a key is generated should be highlighting that it will be coming via email, but we'll think about ways to try and make that language more clear.  

There's actually been a lot of discussion over the years about creating a user experience on api.data.gov for the API key holders, but we've consistently come down on the side of keeping the experience thin and reliable.  The advantages in keeping the service scalable, lightweight, and performant remain paramount and we haven't yet come down on the side of fundamentally expanding the user experience of the developer.  That said, we appreciate the feedback and will take it into account.

**Comment by s2t2** [comment]
Oh hey @gbinal 

Please consider the disadvantage is security. 

If you point me in the right direction, I'd be happy to contribute something. Is the source code in here or [this php app](https://github.com/GSA/data.gov/tree/eebf074d741458c0e70872a40f557bc799487c69/roots-nextdatagov)?

**Comment by gbinal** [comment]
(Good to hear from you!  :)

This repo is the right place.  I might also not be entirely clear on which part of this user experience you're referring to.  Feel free to file any other issues or PRs, but it might make sense to take a step back and articulate what you're thinking about.

**Comment by s2t2** [comment]
As is: when someone requests an API key, it is sent to them via email.

To be: when someone requests an API key, a confirmation email is sent to them to create an account, and after they click the confirmation link in their email, they should be able to login and visit their account page to perform at least the following activities:

  1. View their API Key
  2. Regenerate their API Key, if necessary.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
