### ISSUE TITLE
MVP a catalog of all known APIs

### ISSUE THREAD

**Issue by gbinal** [18F/api.data.gov#512]
There should be a simple HTML page that pulls in the data.gov API to list APIs that are in data.gov.

**Comment by gbinal** [comment]
Resources:
* [APIs in data.gov](https://catalog.data.gov/dataset?res_format=API&_res_format_limit=0)
* [The data.gov API](https://www.data.gov/developers/apis)

**Comment by gbinal** [comment]
* [Where we'll put it](https://api.data.gov/list-of-apis/)
* [source code](https://github.com/18F/api.data.gov/blob/master/source/list-of-apis.html.md)

**Comment by gbinal** [comment]
A 2nd variant would want to be able to pull from a static yaml (or json if needs be) file like this:  

https://github.com/18F/API-All-the-X/blob/18f-pages/_data/individual_apis.yml

**Comment by gbinal** [comment]
It's alive!

https://api.data.gov/list-of-apis/
https://github.com/18F/api.data.gov/blob/master/data/apis.yml

**Comment by gbinal** [comment]
One option - add in a 3rd column indicating which apis are using our service.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
