### ISSUE TITLE
Don't add duplicate HSTS headers

### ISSUE THREAD

**Issue by GUI** [18F/api.data.gov#514]
We add HSTS HTTP headers to our responses. However, if the API backend already included an HSTS header, it leads to 2 HSTS headers being present on the response. This shouldn't necessarily be a big deal, but it would be good to tidy this up. We should either replace any existing HSTS headers (which might make sense if we're responsible for these headers), or not add the header if one is already present (which would allow for agencies to override them perhaps more easily).

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
