### ISSUE TITLE
Adjust IP concurrency limits for Cloud.gov IPs

### ISSUE THREAD

**Issue by GUI** [18F/api.data.gov#515]
Since all API traffic originating from Cloud.gov servers appears to come from 1 of 2 IPs (https://cloud.gov/docs/apps/static-egress/#cloud-gov-egress-ranges), as more Cloud.gov applications come online, we should raise our low-level IP limits that are in place to prevent abuse. We should grant the Cloud.gov IPs a higher limit than most other IPs to account for the fact that many different applications could be making API requests from these IPs.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
