### ISSUE TITLE
deprecate api.data.gov/signup 

### ISSUE THREAD

**Issue by gbinal** [18F/api.data.gov#516]
I think we could do this by:
* Review all of the api docs for our participating agencies.  Website analytics as well.  
* Email all of those that link to it with talking points on why they should embed the form, instructions, and a date at which we're going to take the signup page down.  
* Add in, at the top of that page, links to all of the individual signup pages, pushing down the signup form to below the fold.  
* Warn agencies again.  
* Remove the signup form from that page. 
* Engage with the agencies that haven't embedded the form yet to convey why they must now.  
* Talk about embedding the form as a necessity with all new users from now on.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
