### ISSUE TITLE
change the default embed code to not mention our email address

### ISSUE THREAD

**Issue by gbinal** [18F/api.data.gov#520]
in the contact us link

**Comment by GUI** [comment]
I've adjusted the default embed code to instruct agency admins to fill out more of the variables we want them to: https://github.com/18F/api.data.gov/wiki/User-Manual:-Agencies#embedding-the-api-key-signup-form-on-your-own-documentation-site

Changes: https://github.com/18F/api.data.gov/wiki/User-Manual:-Agencies/_compare/556e9500923cf9b76bf6007f5b3f6d152051434d...264a7a373cc4bb87401aacb106043ffefd2f82d0

But let me know if you spot anything else that needs tweaking and we can reopen this.
