### ISSUE TITLE
Close all of the cracks in the 3rd party customer experience 

### ISSUE THREAD

**Issue by gbinal** [18F/api.data.gov#526]
Those that lead to 3rd party developers getting in touch instead of the appropriate API team.  Steps and progress will be tracked here:  

* [ ] Ensure every API embeds the signup form
* [ ] Ensure every signup form is updated to not reference this team
* [ ] Ensure every signup form is updated so that the confirmation emails don't reference this team.  
* [ ] Ensure every API removes 'credit' links to our service.  
* [ ] Create a new API onboarding checklist that spells out necessary steps.  
* [ ] Ensure that the signup form templates don't mention this team.  
* [ ] Create a new page for 'where to get an API key' that links off to all of the signup pages.  
* [ ] After every API program has embedded signup forms, replace the api.data.gov signup page with ^^^ page.  
* [ ] Change the error page template so that the default points to the 'where to get an API key' page described above, but lets agencies edit it to put in their own link
* [ ] Track any further emails to this team.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
