### ISSUE TITLE
OpenAPI spec documentation for public metrics endpoint

### ISSUE THREAD

**Issue by GUI** [18F/api.data.gov#528]
Publicly document the https://api.gsa.gov/operations/api-data-gov/v0/analytics/summary API for publishing on https://open.gsa.gov/api/apidatagov-metrics/

Note that https://github.com/18F/api.data.gov/issues/527 also need to happen before this can be used publicly.

**Comment by GUI** [comment]
@gbinal: I think this is mostly put together if you wanted to take a look: https://github.com/GSA/open-gsa-redesign/compare/master...GUI:apidatagov-metrics?expand=1

Some questions/notes:

- There's a few items in the docs that are marked "TODO: Remove". These are for old fields that the old metrics page used, but the new metrics page does not. Do you see any reason for keeping these old fields as part of the API? If not, I can remove these.

  The fields to potentially remove are `total_hits`, `hits_by_month`, `total_users`, and `users_by_month`. In all these cases, the new metrics page is using alternate fields underneath the `production_apis` object (eg, `total_hits` becomes `production_apis.all.hits.total`), which is due to our decision to only return API data for what we've deemed "public" APIs. So the numbers will differ between these old and new fields. So unless you see any reason to keep the old style of metrics around, I can remove all these, which might prevent confusion (or needing to explain all these subtle differences).
- Let me know if there's some other better way for you to review this, or if you need any help checking out this branch on your computer to run locally.
- I took a first pass at adding descriptions for all the output fields, but reviews/edits obviously welcome.
- As noted, we need to address #527 before this will really work publicly.

**Comment by gbinal** [comment]
sorry, please tidy up and remove anything, as you see fit.

**Comment by gbinal** [comment]
Thanks again for this.  we're good.  

Closing.
