### ISSUE TITLE
Update the contact us page

### ISSUE THREAD

**Issue by gbinal** [18F/api.data.gov#537]
https://api.data.gov/contact/#apidatagov-service-contact

We should update it with the rest of the agencies who've joined, remove the form, and change our team's contact info to be the email address

**Comment by gbinal** [comment]
Perhaps change the links to the individual programs to be 

Agency 
* Program (linked)
* Program (linked)

so it's easier to browse.  

Also, we should call out more that that is how people need to findsupport, and make us as even more of an afterthought.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
