### ISSUE TITLE
Add 'Contact' to the navbar

### ISSUE THREAD

**Issue by gbinal** [18F/api.data.gov#540]
![Screen Shot 2020-04-29 at 2 33 50 PM](https://user-images.githubusercontent.com/633088/80633335-974cbb00-8a26-11ea-8439-5e80b0f33564.png)

It would make sense to have a link to https://api.data.gov/contact

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
