### ISSUE TITLE
Create `Unique IP Addresses` column to `By Users` page

### ISSUE THREAD

**Issue by gbinal** [18F/api.data.gov#541]
A good idea from the awesome FEC API team, we should add a column that gives the same `Unique IP Addresses` data that one can see individually by clicking through to the email address to the `Filter Logs` page.

**Comment by gbinal** [comment]
I think after the `Hits` and before the `Last Request` columns.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
