### ISSUE TITLE
Change permissions of who can see full API keys 

### ISSUE THREAD

**Issue by gbinal** [18F/api.data.gov#542]
Right now, all agency admins can see full API keys of users for a limited time under limited circumstances.  There were reasons for this when it was configured that way a few years ago, but the reasoning has declined.  We should make it so that agency admins can only see the first few characters, and only super users (the system admins) can see the full API key.

**Comment by GUI** [comment]
Done. https://github.com/NREL/api-umbrella/commit/dc888eccaa9bc5acdb27a2d7380c6d9d5bd9e6fd
