### ISSUE TITLE
Improve e-mail address verification process

### ISSUE THREAD

**Issue by GUI** [18F/api.data.gov#558]
When signing up for API keys and users filling out the "contact us" form, we could take some additional, basic steps to prevent bad signups and spammy contact messages. By validating e-mail addresses a bit better, it would at least cut down on some of these issues (and prevent our system from sending e-mails that will just end up bouncing). The basic improvements are:

- Validate that the domain is a valid domain with MX DNS records. This would at least prevent completely made up e-mail addresses that aren't associated with a real domain. This would also help some situations where users simply typo their actual e-mail domain.
- Block known disposable e-mail address domains. While this certainly won't be fool proof (there's always more domains), we've mainly seen these disposable e-mail domains used for more abusive purposes, so we could at least block some of these known ones.
- Allow easier configuration to block other bad domains.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
