### ISSUE TITLE
JS error with signup form snippet

### ISSUE THREAD

**Issue by sperro** [18F/api.data.gov#561]
I embedded the signup form snippet into my webpage from here [https://api.data.gov/docs/agency-manual/#embedding-the-api-key-signup-form-on-your-own-documentation-site](https://api.data.gov/docs/agency-manual/#embedding-the-api-key-signup-form-on-your-own-documentation-site)
The form is not loading and I'm getting this error "Uncaught ReferenceError: bootbox is not defined at signup_embed.js:35"

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
