### ISSUE TITLE
Enable Dashboard

### ISSUE THREAD

**Issue by shawnjohnson** [18F/api.data.gov#57]
It would be nice to have a few chart and tables available for the administrative dashboard.  Maybe start simple with an activity graph of the last few hours, already filtered to certain API's.

**Comment by GUI** [comment]
Going to go ahead and close this (after probably far too long :), since we've gotten rid of the "Dashboard" link for the nav. We're always happy to consider new ideas for dashboard-type functionality, but we can discuss any of those in more specific issues.
