### ISSUE TITLE
Review datatables.net update

### ISSUE THREAD

**Issue by gbinal** [18F/api.data.gov#620]
Dependabot has [found an update](https://github.com/18F/api.data.gov/security/dependabot/metrics/yarn.lock/datatables.net/open) for datatables.net and suggested an update in [this pull request](https://github.com/18F/api.data.gov/pull/616).    

It's a minor, non-security update that just fixes an obscure functional issue, but updates are always good to make.

**Comment by GUI** [comment]
I've reviewed and tested the PR, and it looks good.

**Comment by gbinal** [comment]
Great.  Merging https://github.com/18F/api.data.gov/pull/616 now...
