### ISSUE TITLE
update Registry openapi spec

### ISSUE THREAD

**Issue by ryanwoldatwork** [18F/api.data.gov#657]
Ensure `digital_service_accounts.json` and `digital_products.json` endpoints have up-to-date documentation.

#### References

* https://github.com/GSA/touchpoints/wiki/api

**Comment by GUI** [comment]
Sorry for the delay. Closing, since we're no longer linking to any of the specific API docs. See https://github.com/18F/api.data.gov/pull/654#issuecomment-1544015941
