### ISSUE TITLE
Update navbar link to data.gov/developers/

### ISSUE THREAD

**Issue by afomi** [18F/api.data.gov#659]
On the page https://api.data.gov/,
the navbar link to https://data.gov/developers/ is 500'ing after data.gov's recent update.

![sdfafsa](https://user-images.githubusercontent.com/67984/235567993-6cb4aaa6-459b-4976-b852-162b4c1736d8.png)

**Comment by GUI** [comment]
This should be resolved by #660 and our new site design to match Data.gov's new design. Thanks for the heads up!
