### ISSUE TITLE
API keys not being sent

### ISSUE THREAD

**Issue by jonquandt** [18F/api.data.gov#670]
This may have been a transient issue, but I received an issue notification on the GovInfo API repo and saw a similar one for Congress.gov where users said they didn't receive their API key after signing up. Happened over the weekend. Could you take a look at the issue and help them get their keys?

https://github.com/usgpo/api/issues/136

Based on the issue below, another user indicated that they were able to generate a key earlier today.
https://github.com/LibraryOfCongress/api.congress.gov/issues/172

**Comment by GUI** [comment]
@jonquandt: Apologies for the issue! We did unfortunately experience an outage in api.data.gov outgoing emails from Thursday night until Sunday morning. Users would not received their API keys for new registrations during this period. It should be fixed now, so if they signup for a new key, it should be delivered now.

We're still sorting through things to setup better monitoring around this and how to better communicate about this issue, but sorry again for the trouble.

**Comment by jonquandt** [comment]
No worries. Will they be able to signup for a new key using the same email or is there another approach needed for that?

**Comment by jonquandt** [comment]
Nevermind - just tested and I was able to get a key. Thanks!
