### ISSUE TITLE
Allow users to view their own API key usage

### ISSUE THREAD

**Issue by GUI** [18F/api.data.gov#76]
We've had several requests from API users who would like to view usage metrics on their own API keys. This might be similar to the analytics we give to admins, but given to users to view on their own API keys.

**Comment by reger** [comment]
Even a simple endpoint to download raw stats would be helpful to users I think, even if there's no UI to it.

**Comment by gbinal** [comment]
This is a good idea, but we've consistently found benefits in keeping the developer user experience light and lean.  

In the coming months, we're going to focus on refining and improving the agency experience and making the overall program more robust.  To that end, I'm going to go ahead and close this issue.
